/* נתוני זרע — קבועים בקוד, לא ב-localStorage.
   ה-store מחזיק מצב משתמש בלבד (תוכנית, פרופילים, מזווה), ולכן אין כאן
   מה להגר בשדרוג. עריכת מנה כותבת העתק תחת אותו מזהה (ראה catalog.js),
   כך שתיקון כאן מגיע גם למי שכבר פתח את האפליקציה — כל עוד הוא לא ערך
   את אותה מנה בעצמו.

   מוסכמה: nutrition_per_100 הוא תמיד לכל 100 של יחידת הבסיס. רוב מצרכי
   הזרע נשמרים בגרמים, ולכן המאקרו שלהם הוא לכל 100 גרם. חלב ושמנת הם
   היוצאים מן הכלל — הם נמכרים בליטרים ונמדדים בכוסות, ולשמור אותם
   בגרמים היה מכריח המרה בכל מתכון. הם מוגדרים ב-ml עם density, והמאקרו
   שלהם הוא לכל 100 מ"ל. */

/** סדר המדפים ברשימת הקניות — הסדר שבו עוברים בסופר. */
export const SHELVES = [
  { id: "produce", name_he: "ירקות ופירות" },
  { id: "meat", name_he: "בשר ועוף" },
  { id: "fish", name_he: "דגים" },
  { id: "dairy_eggs", name_he: "מוצרי חלב וביצים" },
  { id: "dry_goods", name_he: "מוצרים יבשים" },
  { id: "pantry", name_he: "מזווה" },
];

export const INGREDIENTS = [
  /* ---------- ירקות ופירות ---------- */
  {
    id: "ing.onion",
    name_he: "בצל",
    aliases: ["בצל יבש", "בצל לבן"],
    base_unit: "g",
    unit_weight_g: 150,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 40, protein_g: 1.1, fat_g: 0.1, carbs_g: 9.3 },
  },
  {
    id: "ing.tomato",
    name_he: "עגבנייה",
    aliases: ["עגבניות"],
    base_unit: "g",
    unit_weight_g: 120,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 18, protein_g: 0.9, fat_g: 0.2, carbs_g: 3.9 },
  },
  {
    id: "ing.cucumber",
    name_he: "מלפפון",
    aliases: ["מלפפונים"],
    base_unit: "g",
    unit_weight_g: 120,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 15, protein_g: 0.7, fat_g: 0.1, carbs_g: 3.6 },
  },
  {
    id: "ing.bell_pepper",
    name_he: "פלפל",
    aliases: ["פלפל אדום", "גמבה", "פלפלים"],
    base_unit: "g",
    unit_weight_g: 150,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 31, protein_g: 1, fat_g: 0.3, carbs_g: 6 },
  },
  {
    id: "ing.potato",
    name_he: "תפוח אדמה",
    aliases: ["תפוחי אדמה", "תפו״א"],
    base_unit: "g",
    unit_weight_g: 170,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 77, protein_g: 2, fat_g: 0.1, carbs_g: 17 },
  },
  {
    id: "ing.sweet_potato",
    name_he: "בטטה",
    aliases: ["בטטות"],
    base_unit: "g",
    unit_weight_g: 200,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 86, protein_g: 1.6, fat_g: 0.1, carbs_g: 20 },
  },
  {
    id: "ing.carrot",
    name_he: "גזר",
    aliases: ["גזרים"],
    base_unit: "g",
    unit_weight_g: 70,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 41, protein_g: 0.9, fat_g: 0.2, carbs_g: 9.6 },
  },
  {
    id: "ing.zucchini",
    name_he: "קישוא",
    aliases: ["קישואים"],
    base_unit: "g",
    unit_weight_g: 200,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 17, protein_g: 1.2, fat_g: 0.3, carbs_g: 3.1 },
  },
  {
    // שן שום, לא ראש. מתכון נוקב "2 שיני שום", וזה מה שהיחידה מייצגת.
    id: "ing.garlic",
    name_he: "שום",
    aliases: ["שן שום", "שיני שום"],
    base_unit: "g",
    unit_weight_g: 5,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 149, protein_g: 6.4, fat_g: 0.5, carbs_g: 33 },
  },
  {
    id: "ing.lemon",
    name_he: "לימון",
    aliases: ["לימונים"],
    base_unit: "g",
    unit_weight_g: 100,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 29, protein_g: 1.1, fat_g: 0.3, carbs_g: 9.3 },
  },
  {
    id: "ing.parsley",
    name_he: "פטרוזיליה",
    aliases: ["פטרוזיליה טרייה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 36, protein_g: 3, fat_g: 0.8, carbs_g: 6.3 },
  },
  {
    id: "ing.banana",
    name_he: "בננה",
    aliases: ["בננות"],
    base_unit: "g",
    unit_weight_g: 120,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 89, protein_g: 1.1, fat_g: 0.3, carbs_g: 23 },
  },

  /* ---------- בשר ועוף ---------- */
  {
    id: "ing.chicken_breast",
    name_he: "חזה עוף",
    aliases: ["פילה עוף", "חזה עוף טרי"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "meat",
    kosher: "meat",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 165, protein_g: 31, fat_g: 3.6, carbs_g: 0 },
  },
  {
    id: "ing.chicken_thigh",
    name_he: "ירך עוף",
    aliases: ["שוקיים", "פרגיות", "ירכיים"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "meat",
    kosher: "meat",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 209, protein_g: 26, fat_g: 10.9, carbs_g: 0 },
  },
  {
    id: "ing.ground_beef",
    name_he: "בשר בקר טחון",
    aliases: ["בשר טחון", "טחון"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "meat",
    kosher: "meat",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 250, protein_g: 17, fat_g: 20, carbs_g: 0 },
  },

  /* ---------- דגים ----------
     דג הוא פרווה בהלכה, ולכן kosher: "parve" — המדף הנפרד הוא עניין של
     מסלול בסופר בלבד, לא של כשרות. */
  {
    id: "ing.salmon",
    name_he: "פילה סלמון",
    aliases: ["סלמון"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "fish",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 208, protein_g: 20, fat_g: 13, carbs_g: 0 },
  },

  /* ---------- מוצרי חלב וביצים ---------- */
  {
    id: "ing.egg",
    name_he: "ביצה",
    aliases: ["ביצים"],
    base_unit: "g",
    unit_weight_g: 55,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 143, protein_g: 12.6, fat_g: 9.5, carbs_g: 0.7 },
  },
  {
    // ml ולא גרם: חלב נמדד בכוסות ונקנה בליטרים. המאקרו הוא לכל 100 מ"ל.
    id: "ing.milk",
    name_he: "חלב 3%",
    aliases: ["חלב"],
    base_unit: "ml",
    unit_weight_g: null,
    density_g_per_ml: 1.03,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 63, protein_g: 3.3, fat_g: 3.4, carbs_g: 4.8 },
  },
  {
    id: "ing.cream",
    name_he: "שמנת לבישול 15%",
    aliases: ["שמנת מתוקה", "שמנת"],
    base_unit: "ml",
    unit_weight_g: null,
    density_g_per_ml: 1,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 160, protein_g: 2.5, fat_g: 15, carbs_g: 3.5 },
  },
  {
    // גביע יוגורט — משקל היחידה משתנה בין מותגים, ולכן unit_weight_g נשאר null.
    // מנה שנוקבת "1 יח'" תיפול למסלול "לבדוק ידנית" במקום להמציא המרה.
    id: "ing.yogurt",
    name_he: "יוגורט טבעי",
    aliases: ["גביע יוגורט"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 61, protein_g: 3.5, fat_g: 3.3, carbs_g: 4.7 },
  },
  {
    id: "ing.bulgarian_cheese",
    name_he: "גבינה בולגרית 16%",
    aliases: ["בולגרית", "גבינה מלוחה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 208, protein_g: 14, fat_g: 16, carbs_g: 1 },
  },
  {
    // פרוסה, לא חבילה — מתכון נוקב "2 פרוסות גבינה צהובה".
    id: "ing.yellow_cheese",
    name_he: "גבינה צהובה 28%",
    aliases: ["גבינה צהובה", "עמק", "גילבוע"],
    base_unit: "g",
    unit_weight_g: 20,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 350, protein_g: 25, fat_g: 27, carbs_g: 1.5 },
  },
  {
    id: "ing.mozzarella",
    name_he: "מוצרלה",
    aliases: ["גבינת פיצה", "מוצרלה מגורדת"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 280, protein_g: 22, fat_g: 22, carbs_g: 2.2 },
  },
  {
    id: "ing.parmesan",
    name_he: "פרמזן",
    aliases: ["גבינה קשה", "פרמז'ן"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 392, protein_g: 35.8, fat_g: 25.8, carbs_g: 3.2 },
  },

  /* ---------- מוצרים יבשים ---------- */
  {
    id: "ing.rice",
    name_he: "אורז לבן",
    aliases: ["אורז"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 360, protein_g: 6.6, fat_g: 0.6, carbs_g: 79 },
  },
  {
    id: "ing.pasta",
    name_he: "פסטה",
    aliases: ["ספגטי", "פנה", "מקרוני"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 371, protein_g: 13, fat_g: 1.5, carbs_g: 75 },
  },
  {
    // מוצר נפרד מפסטה בסופר ובארון, גם אם הערך התזונתי זהה. מיזוג שלהם
    // היה שולח לקנות חבילת ספגטי בשביל מרק.
    id: "ing.soup_noodles",
    name_he: "אטריות למרק",
    aliases: ["אטריות", "נודלס"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 371, protein_g: 13, fat_g: 1.5, carbs_g: 75 },
  },
  {
    id: "ing.ptitim",
    name_he: "פתיתים",
    aliases: ["פתיתים ישראליים", "בן גוריון"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 357, protein_g: 12, fat_g: 1.5, carbs_g: 73 },
  },
  {
    id: "ing.quinoa",
    name_he: "קינואה",
    aliases: ["קינואה לבנה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 368, protein_g: 14, fat_g: 6, carbs_g: 64 },
  },
  {
    id: "ing.oats",
    name_he: "שיבולת שועל",
    aliases: ["קוואקר", "שיבולת שועל דקה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 389, protein_g: 16.9, fat_g: 6.9, carbs_g: 66 },
  },
  {
    id: "ing.lentils",
    name_he: "עדשים",
    aliases: ["עדשים כתומות", "עדשים ירוקות"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 353, protein_g: 25, fat_g: 1.1, carbs_g: 60 },
  },
  {
    id: "ing.chickpeas",
    name_he: "גרגירי חומוס יבשים",
    aliases: ["חומוס יבש", "גרגירי חומוס"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 364, protein_g: 19, fat_g: 6, carbs_g: 61 },
  },
  {
    // משומרת ומסוננת — הערך התזונתי שונה מהותית מיבשה, ולכן מצרך נפרד.
    id: "ing.canned_beans",
    name_he: "שעועית אדומה משומרת",
    aliases: ["שעועית משומרת", "שעועית אדומה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 127, protein_g: 8.7, fat_g: 0.5, carbs_g: 22.8 },
  },
  {
    id: "ing.canned_tuna",
    name_he: "טונה בשימורים",
    aliases: ["טונה", "קופסת טונה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 186, protein_g: 25.5, fat_g: 8.2, carbs_g: 0 },
  },
  {
    id: "ing.corn",
    name_he: "תירס משומר",
    aliases: ["תירס", "קופסת תירס"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 86, protein_g: 3.2, fat_g: 1.2, carbs_g: 19 },
  },
  {
    id: "ing.breadcrumbs",
    name_he: "פירורי לחם",
    aliases: ["פירורי ציפוי"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 395, protein_g: 13, fat_g: 5.3, carbs_g: 72 },
  },
  {
    id: "ing.bread",
    name_he: "לחם פרוס",
    aliases: ["לחם", "פרוסת לחם"],
    base_unit: "g",
    unit_weight_g: 30,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 265, protein_g: 9, fat_g: 3.2, carbs_g: 49 },
  },
  {
    id: "ing.pita",
    name_he: "פיתה",
    aliases: ["פיתות"],
    base_unit: "g",
    unit_weight_g: 70,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 275, protein_g: 9, fat_g: 1.2, carbs_g: 55 },
  },
  {
    id: "ing.flour",
    name_he: "קמח לבן",
    aliases: ["קמח"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 364, protein_g: 10, fat_g: 1, carbs_g: 76 },
  },
  {
    id: "ing.yeast",
    name_he: "שמרים יבשים",
    aliases: ["שמרים"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 325, protein_g: 40, fat_g: 7.6, carbs_g: 41 },
  },

  /* ---------- מזווה ----------
     pantry_staple מסמן "תמיד יש בבית" ומוריד את המצרך מרשימת הקניות.
     שמור לתבלינים ולשמן בלבד: כל דבר שבאמת נגמר ושצריך לזכור לקנות
     חייב להישאר ברשימה, אחרת ההשמטה השקטה היא בדיוק סוג הטעות
     שהמנוע נבנה כדי למנוע. */
  {
    id: "ing.olive_oil",
    name_he: "שמן זית",
    aliases: ["שמן"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: 0.91,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 884, protein_g: 0, fat_g: 100, carbs_g: 0 },
  },
  {
    id: "ing.salt",
    name_he: "מלח",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 0, protein_g: 0, fat_g: 0, carbs_g: 0 },
  },
  {
    id: "ing.black_pepper",
    name_he: "פלפל שחור",
    aliases: ["פלפל שחור טחון"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 251, protein_g: 10, fat_g: 3.3, carbs_g: 64 },
  },
  {
    id: "ing.paprika",
    name_he: "פפריקה",
    aliases: ["פפריקה מתוקה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 282, protein_g: 14, fat_g: 13, carbs_g: 54 },
  },
  {
    id: "ing.cumin",
    name_he: "כמון",
    aliases: ["כמון טחון"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 375, protein_g: 18, fat_g: 22, carbs_g: 44 },
  },
  {
    id: "ing.tomato_paste",
    name_he: "רסק עגבניות",
    aliases: ["רסק", "רסק עגבניות מרוכז"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 82, protein_g: 4.3, fat_g: 0.5, carbs_g: 19 },
  },
  {
    id: "ing.tahini",
    name_he: "טחינה גולמית",
    aliases: ["טחינה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 595, protein_g: 17, fat_g: 53, carbs_g: 21 },
  },
  {
    id: "ing.mayonnaise",
    name_he: "מיונז",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 680, protein_g: 1, fat_g: 75, carbs_g: 1.5 },
  },
  {
    id: "ing.honey",
    name_he: "דבש",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 304, protein_g: 0.3, fat_g: 0, carbs_g: 82 },
  },
  {
    id: "ing.sugar",
    name_he: "סוכר",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 387, protein_g: 0, fat_g: 0, carbs_g: 100 },
  },
];

/* כמויות המנה הן תמיד למנה בודדת אחת. ההכפלה קורה רק בשכבת התוכנית.

   ── למה הקטלוג בגודל הזה ────────────────────────────────────────────
   גרסה קודמת נזרעה בשלוש מנות, וזה נראה מספיק כי בכל מקרה מוסיפים
   מנות בעצמך. בפועל זה שבר שני דברים: התקנה טרייה נחתה על מתכנן שאין
   בו מה לתכנן, והבלוק "לא בישלנו מזמן" — שמוסתר מתחת לשבע מנות —
   מעולם לא רץ אצל מי שלא הקליד ידנית עוד ארבע. קטלוג פותח צריך להיות
   גדול מספיק כדי שהשבוע הראשון יתוכנן בלי הקלדה. */
export const DISHES = [
  {
    id: "dish.schnitzel_chips",
    name_he: "שניצל וצ'יפס",
    kosher: "meat",
    effort: "medium",
    time_min: 35,
    ingredients: [
      { ingredient_id: "ing.chicken_breast", qty: 150, unit: "g" },
      { ingredient_id: "ing.egg", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.breadcrumbs", qty: 40, unit: "g" },
      { ingredient_id: "ing.potato", qty: 250, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 20, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["לצפות את השניצל מראש"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.rice_veg",
    name_he: "אורז עם בצל ועגבניות",
    kosher: "parve",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.rice", qty: 80, unit: "g" },
      { ingredient_id: "ing.onion", qty: 2, unit: "unit" },
      { ingredient_id: "ing.tomato", qty: 2, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.veg_omelette",
    name_he: "חביתת ירק עם יוגורט",
    kosher: "dairy",
    effort: "low",
    time_min: 15,
    ingredients: [
      { ingredient_id: "ing.egg", qty: 2, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 150, unit: "g" },
      { ingredient_id: "ing.tomato", qty: 1, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
      { ingredient_id: "ing.yogurt", qty: 1, unit: "unit" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.shakshuka",
    name_he: "שקשוקה",
    kosher: "parve",
    effort: "low",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.egg", qty: 2, unit: "unit" },
      { ingredient_id: "ing.tomato", qty: 2, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.bell_pepper", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.tomato_paste", qty: 20, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.paprika", qty: 3, unit: "g" },
      { ingredient_id: "ing.cumin", qty: 2, unit: "g" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick", "breakfast"],
    macros_override: null,
  },
  {
    id: "dish.israeli_salad_cheese",
    name_he: "סלט ירקות עם גבינה בולגרית",
    kosher: "dairy",
    effort: "low",
    time_min: 10,
    ingredients: [
      { ingredient_id: "ing.cucumber", qty: 1.5, unit: "unit" },
      { ingredient_id: "ing.tomato", qty: 1.5, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 0.25, unit: "unit" },
      { ingredient_id: "ing.parsley", qty: 10, unit: "g" },
      { ingredient_id: "ing.bulgarian_cheese", qty: 50, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.lemon", qty: 0.25, unit: "unit" },
      { ingredient_id: "ing.salt", qty: 1, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick", "breakfast"],
    macros_override: null,
  },
  {
    id: "dish.cheese_toast",
    name_he: "טוסט גבינה וירקות",
    kosher: "dairy",
    effort: "low",
    time_min: 8,
    ingredients: [
      { ingredient_id: "ing.bread", qty: 2, unit: "unit" },
      { ingredient_id: "ing.yellow_cheese", qty: 2, unit: "unit" },
      { ingredient_id: "ing.tomato", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 5, unit: "ml" },
    ],
    prep_ahead: [],
    tags: ["quick", "breakfast"],
    macros_override: null,
  },
  {
    id: "dish.oatmeal",
    name_he: "דייסת שיבולת שועל",
    kosher: "dairy",
    effort: "low",
    time_min: 10,
    ingredients: [
      { ingredient_id: "ing.oats", qty: 50, unit: "g" },
      { ingredient_id: "ing.milk", qty: 250, unit: "ml" },
      { ingredient_id: "ing.banana", qty: 1, unit: "unit" },
      { ingredient_id: "ing.honey", qty: 10, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick", "breakfast"],
    macros_override: null,
  },
  {
    id: "dish.roast_chicken_potatoes",
    name_he: "עוף בתנור עם תפוחי אדמה",
    kosher: "meat",
    effort: "low",
    time_min: 70,
    ingredients: [
      { ingredient_id: "ing.chicken_thigh", qty: 200, unit: "g" },
      { ingredient_id: "ing.potato", qty: 250, unit: "g" },
      { ingredient_id: "ing.onion", qty: 1, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.paprika", qty: 4, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
      { ingredient_id: "ing.black_pepper", qty: 1, unit: "g" },
    ],
    prep_ahead: ["לתבל את העוף מראש ולהשאיר במקרר"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.meatballs_tomato",
    name_he: "קציצות בקר ברוטב עגבניות",
    kosher: "meat",
    effort: "medium",
    time_min: 45,
    ingredients: [
      { ingredient_id: "ing.ground_beef", qty: 150, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.egg", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.breadcrumbs", qty: 25, unit: "g" },
      { ingredient_id: "ing.tomato_paste", qty: 40, unit: "g" },
      { ingredient_id: "ing.tomato", qty: 1, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
      { ingredient_id: "ing.black_pepper", qty: 1, unit: "g" },
    ],
    prep_ahead: ["לגלגל את הקציצות מראש"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.pasta_bolognese",
    name_he: "פסטה בולונז",
    kosher: "meat",
    effort: "medium",
    time_min: 40,
    ingredients: [
      { ingredient_id: "ing.pasta", qty: 100, unit: "g" },
      { ingredient_id: "ing.ground_beef", qty: 120, unit: "g" },
      { ingredient_id: "ing.tomato_paste", qty: 50, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["הרוטב יוצא טוב יותר כשמכינים אותו יום קודם"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.chicken_soup",
    name_he: "מרק עוף עם אטריות",
    kosher: "meat",
    effort: "medium",
    time_min: 60,
    ingredients: [
      { ingredient_id: "ing.chicken_thigh", qty: 150, unit: "g" },
      { ingredient_id: "ing.carrot", qty: 1, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.potato", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.soup_noodles", qty: 40, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
      { ingredient_id: "ing.black_pepper", qty: 1, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.shawarma_pita",
    name_he: "שווארמה ביתית בפיתה",
    kosher: "meat",
    effort: "medium",
    time_min: 30,
    ingredients: [
      { ingredient_id: "ing.chicken_thigh", qty: 180, unit: "g" },
      { ingredient_id: "ing.pita", qty: 1, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.tahini", qty: 30, unit: "g" },
      { ingredient_id: "ing.cucumber", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.tomato", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.cumin", qty: 3, unit: "g" },
      { ingredient_id: "ing.paprika", qty: 2, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: ["לתבל את העוף בערב הקודם"],
    tags: [],
    macros_override: null,
  },
  {
    id: "dish.beef_chili",
    name_he: "צ'ילי בשר ושעועית",
    kosher: "meat",
    effort: "medium",
    time_min: 50,
    ingredients: [
      { ingredient_id: "ing.ground_beef", qty: 120, unit: "g" },
      { ingredient_id: "ing.canned_beans", qty: 150, unit: "g" },
      { ingredient_id: "ing.tomato_paste", qty: 40, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.bell_pepper", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.cumin", qty: 3, unit: "g" },
      { ingredient_id: "ing.paprika", qty: 3, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.mejadra",
    name_he: "מג'דרה",
    kosher: "parve",
    effort: "low",
    time_min: 40,
    ingredients: [
      { ingredient_id: "ing.rice", qty: 70, unit: "g" },
      { ingredient_id: "ing.lentils", qty: 50, unit: "g" },
      { ingredient_id: "ing.onion", qty: 1.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 20, unit: "ml" },
      { ingredient_id: "ing.cumin", qty: 3, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["אפשר לטגן את הבצל מראש"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.pasta_cream",
    name_he: "פסטה ברוטב עגבניות ושמנת",
    kosher: "dairy",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.pasta", qty: 100, unit: "g" },
      { ingredient_id: "ing.tomato_paste", qty: 40, unit: "g" },
      { ingredient_id: "ing.cream", qty: 60, unit: "ml" },
      { ingredient_id: "ing.parmesan", qty: 15, unit: "g" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.homemade_pizza",
    name_he: "פיצה ביתית",
    kosher: "dairy",
    effort: "high",
    time_min: 60,
    ingredients: [
      { ingredient_id: "ing.flour", qty: 120, unit: "g" },
      { ingredient_id: "ing.yeast", qty: 3, unit: "g" },
      { ingredient_id: "ing.mozzarella", qty: 80, unit: "g" },
      { ingredient_id: "ing.tomato_paste", qty: 50, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.sugar", qty: 3, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["להכין את הבצק מראש ולתת לו לתפוח במקרר"],
    tags: [],
    macros_override: null,
  },
  {
    id: "dish.quinoa_salad",
    name_he: "סלט קינואה עם ירקות",
    kosher: "parve",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.quinoa", qty: 60, unit: "g" },
      { ingredient_id: "ing.cucumber", qty: 1, unit: "unit" },
      { ingredient_id: "ing.tomato", qty: 1, unit: "unit" },
      { ingredient_id: "ing.parsley", qty: 15, unit: "g" },
      { ingredient_id: "ing.lemon", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: ["אפשר לבשל את הקינואה מראש"],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.hummus",
    name_he: "חומוס ביתי",
    kosher: "parve",
    effort: "medium",
    time_min: 40,
    ingredients: [
      { ingredient_id: "ing.chickpeas", qty: 80, unit: "g" },
      { ingredient_id: "ing.tahini", qty: 40, unit: "g" },
      { ingredient_id: "ing.lemon", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.garlic", qty: 1, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.cumin", qty: 2, unit: "g" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: ["להשרות את הגרגירים מלילה קודם"],
    tags: [],
    macros_override: null,
  },
  {
    id: "dish.lentil_soup",
    name_he: "מרק עדשים",
    kosher: "parve",
    effort: "low",
    time_min: 45,
    ingredients: [
      { ingredient_id: "ing.lentils", qty: 70, unit: "g" },
      { ingredient_id: "ing.carrot", qty: 1, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.potato", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.cumin", qty: 3, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.pasta_tomato_garlic",
    name_he: "פסטה ברוטב עגבניות ושום",
    kosher: "parve",
    effort: "low",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.pasta", qty: 100, unit: "g" },
      { ingredient_id: "ing.tomato_paste", qty: 50, unit: "g" },
      { ingredient_id: "ing.tomato", qty: 1, unit: "unit" },
      { ingredient_id: "ing.garlic", qty: 3, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.roasted_veg",
    name_he: "ירקות בתנור",
    kosher: "parve",
    effort: "low",
    time_min: 45,
    ingredients: [
      { ingredient_id: "ing.sweet_potato", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.potato", qty: 1, unit: "unit" },
      { ingredient_id: "ing.carrot", qty: 1, unit: "unit" },
      { ingredient_id: "ing.zucchini", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 20, unit: "ml" },
      { ingredient_id: "ing.paprika", qty: 3, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["אפשר לחתוך את הירקות מראש"],
    tags: [],
    macros_override: null,
  },
  {
    id: "dish.baked_salmon",
    name_he: "סלמון בתנור עם לימון",
    kosher: "parve",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.salmon", qty: 180, unit: "g" },
      { ingredient_id: "ing.lemon", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.garlic", qty: 1, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
      { ingredient_id: "ing.black_pepper", qty: 1, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.tuna_salad",
    name_he: "סלט טונה",
    kosher: "parve",
    effort: "low",
    time_min: 10,
    ingredients: [
      { ingredient_id: "ing.canned_tuna", qty: 80, unit: "g" },
      { ingredient_id: "ing.mayonnaise", qty: 20, unit: "g" },
      { ingredient_id: "ing.cucumber", qty: 1, unit: "unit" },
      { ingredient_id: "ing.corn", qty: 40, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.25, unit: "unit" },
      { ingredient_id: "ing.lemon", qty: 0.25, unit: "unit" },
      { ingredient_id: "ing.salt", qty: 1, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.ptitim_veg",
    name_he: "פתיתים עם ירקות",
    kosher: "parve",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.ptitim", qty: 90, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.bell_pepper", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.carrot", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick", "comfort"],
    macros_override: null,
  },
  {
    id: "dish.fried_rice_egg",
    name_he: "אורז מוקפץ עם ירקות וביצה",
    kosher: "parve",
    effort: "low",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.rice", qty: 80, unit: "g" },
      { ingredient_id: "ing.egg", qty: 1.5, unit: "unit" },
      { ingredient_id: "ing.carrot", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.bell_pepper", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: ["יוצא הכי טוב עם אורז מאתמול"],
    tags: ["quick"],
    macros_override: null,
  },
];

/** פרופילי ברירת מחדל — נזרעים למצב המשתמש בטעינה הראשונה. */
export const DEFAULT_PROFILES = [
  {
    id: "p1",
    name_he: "ירין",
    targets: { kcal: 2200, protein_g: 150, fat_g: 70, carbs_g: 230 },
    dislikes: [],
  },
  {
    id: "p2",
    name_he: "בן/בת הזוג",
    targets: { kcal: 1800, protein_g: 110, fat_g: 60, carbs_g: 190 },
    dislikes: [],
  },
];

const INGREDIENT_BY_ID = new Map(INGREDIENTS.map((ing) => [ing.id, ing]));
const DISH_BY_ID = new Map(DISHES.map((dish) => [dish.id, dish]));

export function getIngredient(id) {
  return INGREDIENT_BY_ID.get(id) || null;
}

export function getDish(id) {
  return DISH_BY_ID.get(id) || null;
}

export function getShelfName(id) {
  const shelf = SHELVES.find((s) => s.id === id);
  return shelf ? shelf.name_he : id;
}
