/* נתוני זרע — קבועים בקוד, לא ב-localStorage.
   ה-store מחזיק מצב משתמש בלבד (תוכנית, פרופילים, מזווה), ולכן אין כאן
   מה להגר בשדרוג. עריכת מנה כותבת העתק תחת אותו מזהה (ראה catalog.js),
   כך שתיקון כאן מגיע גם למי שכבר פתח את האפליקציה — כל עוד הוא לא ערך
   את אותה מנה בעצמו.

   מוסכמה: nutrition_per_100 הוא תמיד לכל 100 של יחידת הבסיס. רוב מצרכי
   הזרע נשמרים בגרמים, ולכן המאקרו שלהם הוא לכל 100 גרם. חלב ושמנת הם
   היוצאים מן הכלל — הם נמכרים בליטרים ונמדדים בכוסות, ולשמור אותם
   בגרמים היה מכריח המרה בכל מתכון. הם מוגדרים ב-ml עם density, והמאקרו
   שלהם הוא לכל 100 מ"ל. */

/** סדר המדפים ברשימת הקניות — הסדר שבו עוברים בסופר. */
export const SHELVES = [
  { id: "produce", name_he: "ירקות ופירות" },
  { id: "meat", name_he: "בשר ועוף" },
  { id: "fish", name_he: "דגים" },
  { id: "dairy_eggs", name_he: "מוצרי חלב וביצים" },
  { id: "chilled", name_he: "ממרחים וסלטים מוכנים" },
  { id: "dry_goods", name_he: "מוצרים יבשים" },
  { id: "drinks", name_he: "משקאות" },
  { id: "pantry", name_he: "מזווה" },
];

export const INGREDIENTS = [
  /* ---------- ירקות ופירות ---------- */
  {
    id: "ing.onion",
    name_he: "בצל",
    aliases: ["בצל יבש", "בצל לבן"],
    base_unit: "g",
    unit_weight_g: 150,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 40, protein_g: 1.1, fat_g: 0.1, carbs_g: 9.3 },
  },
  {
    id: "ing.tomato",
    name_he: "עגבנייה",
    aliases: ["עגבניות"],
    base_unit: "g",
    unit_weight_g: 120,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 18, protein_g: 0.9, fat_g: 0.2, carbs_g: 3.9 },
  },
  {
    id: "ing.cucumber",
    name_he: "מלפפון",
    aliases: ["מלפפונים"],
    base_unit: "g",
    unit_weight_g: 120,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 15, protein_g: 0.7, fat_g: 0.1, carbs_g: 3.6 },
  },
  {
    id: "ing.bell_pepper",
    name_he: "פלפל",
    aliases: ["פלפל אדום", "גמבה", "פלפלים"],
    base_unit: "g",
    unit_weight_g: 150,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 31, protein_g: 1, fat_g: 0.3, carbs_g: 6 },
  },
  {
    id: "ing.potato",
    name_he: "תפוח אדמה",
    aliases: ["תפוחי אדמה", "תפו״א"],
    base_unit: "g",
    unit_weight_g: 170,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 77, protein_g: 2, fat_g: 0.1, carbs_g: 17 },
  },
  {
    id: "ing.sweet_potato",
    name_he: "בטטה",
    aliases: ["בטטות"],
    base_unit: "g",
    unit_weight_g: 200,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 86, protein_g: 1.6, fat_g: 0.1, carbs_g: 20 },
  },
  {
    id: "ing.carrot",
    name_he: "גזר",
    aliases: ["גזרים"],
    base_unit: "g",
    unit_weight_g: 70,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 41, protein_g: 0.9, fat_g: 0.2, carbs_g: 9.6 },
  },
  {
    id: "ing.zucchini",
    name_he: "קישוא",
    aliases: ["קישואים"],
    base_unit: "g",
    unit_weight_g: 200,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 17, protein_g: 1.2, fat_g: 0.3, carbs_g: 3.1 },
  },
  {
    // שן שום, לא ראש. מתכון נוקב "2 שיני שום", וזה מה שהיחידה מייצגת.
    id: "ing.garlic",
    name_he: "שום",
    aliases: ["שן שום", "שיני שום"],
    base_unit: "g",
    unit_weight_g: 5,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 149, protein_g: 6.4, fat_g: 0.5, carbs_g: 33 },
  },
  {
    id: "ing.lemon",
    name_he: "לימון",
    aliases: ["לימונים"],
    base_unit: "g",
    unit_weight_g: 100,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 29, protein_g: 1.1, fat_g: 0.3, carbs_g: 9.3 },
  },
  {
    id: "ing.parsley",
    name_he: "פטרוזיליה",
    aliases: ["פטרוזיליה טרייה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 36, protein_g: 3, fat_g: 0.8, carbs_g: 6.3 },
  },
  {
    id: "ing.banana",
    name_he: "בננה",
    aliases: ["בננות"],
    base_unit: "g",
    unit_weight_g: 120,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 89, protein_g: 1.1, fat_g: 0.3, carbs_g: 23 },
  },

  {
    id: "ing.eggplant",
    name_he: "חציל",
    aliases: ["חצילים"],
    base_unit: "g",
    unit_weight_g: 300,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 25, protein_g: 1, fat_g: 0.2, carbs_g: 6 },
  },
  {
    id: "ing.cauliflower",
    name_he: "כרובית",
    aliases: ["כרוביות"],
    base_unit: "g",
    unit_weight_g: 600,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 25, protein_g: 1.9, fat_g: 0.3, carbs_g: 5 },
  },
  {
    id: "ing.green_beans",
    name_he: "שעועית ירוקה",
    aliases: ["שעועית"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 31, protein_g: 1.8, fat_g: 0.2, carbs_g: 7 },
  },
  {
    id: "ing.mushroom",
    name_he: "פטריות",
    aliases: ["פטרייה", "שמפיניון"],
    base_unit: "g",
    unit_weight_g: 20,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 22, protein_g: 3.1, fat_g: 0.3, carbs_g: 3.3 },
  },
  {
    id: "ing.scallion",
    name_he: "בצל ירוק",
    aliases: ["בצל עלים"],
    base_unit: "g",
    unit_weight_g: 15,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 32, protein_g: 1.8, fat_g: 0.2, carbs_g: 7.3 },
  },
  {
    id: "ing.cilantro",
    name_he: "כוסברה",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 23, protein_g: 2.1, fat_g: 0.5, carbs_g: 3.7 },
  },
  {
    id: "ing.hot_pepper",
    name_he: "פלפל חריף",
    aliases: ["צ'ילי"],
    base_unit: "g",
    unit_weight_g: 15,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 40, protein_g: 1.9, fat_g: 0.4, carbs_g: 9 },
  },
  {
    id: "ing.ginger",
    name_he: "ג'ינג'ר",
    aliases: ["זנגביל"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 80, protein_g: 1.8, fat_g: 0.8, carbs_g: 18 },
  },

  /* ---------- בשר ועוף ---------- */
  {
    id: "ing.chicken_breast",
    name_he: "חזה עוף",
    aliases: ["פילה עוף", "חזה עוף טרי"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "meat",
    kosher: "meat",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 165, protein_g: 31, fat_g: 3.6, carbs_g: 0 },
  },
  {
    id: "ing.chicken_thigh",
    name_he: "ירך עוף",
    aliases: ["שוקיים", "פרגיות", "ירכיים"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "meat",
    kosher: "meat",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 209, protein_g: 26, fat_g: 10.9, carbs_g: 0 },
  },
  {
    id: "ing.ground_beef",
    name_he: "בשר בקר טחון",
    aliases: ["בשר טחון", "טחון"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "meat",
    kosher: "meat",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 250, protein_g: 17, fat_g: 20, carbs_g: 0 },
  },

  {
    id: "ing.beef_strips",
    name_he: "רצועות בקר",
    aliases: ["בקר לפרוסות", "אונטריב לרצועות"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "meat",
    kosher: "meat",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 187, protein_g: 21, fat_g: 11, carbs_g: 0 },
  },
  {
    id: "ing.entrecote",
    name_he: "אנטריקוט",
    aliases: ["סטייק אנטריקוט"],
    base_unit: "g",
    unit_weight_g: 250,
    density_g_per_ml: null,
    shelf: "meat",
    kosher: "meat",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 291, protein_g: 24, fat_g: 21, carbs_g: 0 },
  },
  {
    id: "ing.whole_chicken",
    name_he: "עוף שלם",
    aliases: ["עוף לחלקים", "כרעיים"],
    base_unit: "g",
    unit_weight_g: 1500,
    density_g_per_ml: null,
    shelf: "meat",
    kosher: "meat",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 215, protein_g: 18, fat_g: 15, carbs_g: 0 },
  },

  /* ---------- דגים ----------
     דג הוא פרווה בהלכה, ולכן kosher: "parve" — המדף הנפרד הוא עניין של
     מסלול בסופר בלבד, לא של כשרות. */
  {
    id: "ing.salmon",
    name_he: "פילה סלמון",
    aliases: ["סלמון"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "fish",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 208, protein_g: 20, fat_g: 13, carbs_g: 0 },
  },

  {
    id: "ing.tilapia",
    name_he: "פילה אמנון",
    aliases: ["אמנון", "מושט", "טילפיה"],
    base_unit: "g",
    unit_weight_g: 150,
    density_g_per_ml: null,
    shelf: "fish",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 96, protein_g: 20, fat_g: 1.7, carbs_g: 0 },
  },

  /* ---------- מוצרי חלב וביצים ---------- */
  {
    id: "ing.egg",
    name_he: "ביצה",
    aliases: ["ביצים"],
    base_unit: "g",
    unit_weight_g: 55,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 143, protein_g: 12.6, fat_g: 9.5, carbs_g: 0.7 },
  },
  {
    // ml ולא גרם: חלב נמדד בכוסות ונקנה בליטרים. המאקרו הוא לכל 100 מ"ל.
    //
    // unit_weight_g הוא משקל הכוס (200 מ"ל × 1.03), ולא נפחה. בלעדיו
    // "כוס חלב" בהוספה מהירה נופלת למסלול הידני — בדיוק במקום שבו כל
    // הרווח הוא הקשה אחת. ההמרה עוברת דרך הגרמים ולכן הצפיפות נדרשת.
    id: "ing.milk",
    name_he: "חלב 3%",
    aliases: ["חלב"],
    base_unit: "ml",
    unit_weight_g: 206,
    density_g_per_ml: 1.03,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 63, protein_g: 3.3, fat_g: 3.4, carbs_g: 4.8 },
  },
  {
    id: "ing.cream",
    name_he: "שמנת לבישול 15%",
    aliases: ["שמנת מתוקה", "שמנת"],
    base_unit: "ml",
    unit_weight_g: null,
    density_g_per_ml: 1,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 160, protein_g: 2.5, fat_g: 15, carbs_g: 3.5 },
  },
  {
    // גביע יוגורט — משקל היחידה משתנה בין מותגים, ולכן unit_weight_g נשאר null.
    // מנה שנוקבת "1 יח'" תיפול למסלול "לבדוק ידנית" במקום להמציא המרה.
    id: "ing.yogurt",
    name_he: "יוגורט טבעי",
    aliases: ["גביע יוגורט"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 61, protein_g: 3.5, fat_g: 3.3, carbs_g: 4.7 },
  },
  {
    id: "ing.bulgarian_cheese",
    name_he: "גבינה בולגרית 16%",
    aliases: ["בולגרית", "גבינה מלוחה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 208, protein_g: 14, fat_g: 16, carbs_g: 1 },
  },
  {
    // פרוסה, לא חבילה — מתכון נוקב "2 פרוסות גבינה צהובה".
    id: "ing.yellow_cheese",
    name_he: "גבינה צהובה 28%",
    aliases: ["גבינה צהובה", "עמק", "גילבוע"],
    base_unit: "g",
    unit_weight_g: 20,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 350, protein_g: 25, fat_g: 27, carbs_g: 1.5 },
  },
  {
    id: "ing.mozzarella",
    name_he: "מוצרלה",
    aliases: ["גבינת פיצה", "מוצרלה מגורדת"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 280, protein_g: 22, fat_g: 22, carbs_g: 2.2 },
  },
  {
    id: "ing.parmesan",
    name_he: "פרמזן",
    aliases: ["גבינה קשה", "פרמז'ן"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 392, protein_g: 35.8, fat_g: 25.8, carbs_g: 3.2 },
  },

  {
    id: "ing.feta",
    name_he: "גבינת פטה",
    aliases: ["פטה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 264, protein_g: 14, fat_g: 21, carbs_g: 4 },
  },
  {
    id: "ing.white_cheese",
    name_he: "גבינה לבנה 5%",
    aliases: ["גבינה לבנה"],
    base_unit: "g",
    unit_weight_g: 250,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 96, protein_g: 8.5, fat_g: 5, carbs_g: 3.7 },
  },
  {
    id: "ing.goat_cheese",
    name_he: "גבינת עיזים",
    aliases: ["גבינת עזים", "עיזים"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 268, protein_g: 18, fat_g: 21, carbs_g: 2.5 },
  },

  /* ---------- מוצרים יבשים ---------- */
  {
    id: "ing.rice",
    name_he: "אורז לבן",
    aliases: ["אורז"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 360, protein_g: 6.6, fat_g: 0.6, carbs_g: 79 },
  },
  {
    id: "ing.pasta",
    name_he: "פסטה",
    aliases: ["ספגטי", "פנה", "מקרוני"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 371, protein_g: 13, fat_g: 1.5, carbs_g: 75 },
  },
  {
    // מוצר נפרד מפסטה בסופר ובארון, גם אם הערך התזונתי זהה. מיזוג שלהם
    // היה שולח לקנות חבילת ספגטי בשביל מרק.
    id: "ing.soup_noodles",
    name_he: "אטריות למרק",
    aliases: ["אטריות", "נודלס"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 371, protein_g: 13, fat_g: 1.5, carbs_g: 75 },
  },
  {
    id: "ing.ptitim",
    name_he: "פתיתים",
    aliases: ["פתיתים ישראליים", "בן גוריון"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 357, protein_g: 12, fat_g: 1.5, carbs_g: 73 },
  },
  {
    id: "ing.quinoa",
    name_he: "קינואה",
    aliases: ["קינואה לבנה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 368, protein_g: 14, fat_g: 6, carbs_g: 64 },
  },
  {
    id: "ing.oats",
    name_he: "שיבולת שועל",
    aliases: ["קוואקר", "שיבולת שועל דקה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 389, protein_g: 16.9, fat_g: 6.9, carbs_g: 66 },
  },
  {
    id: "ing.lentils",
    name_he: "עדשים",
    aliases: ["עדשים כתומות", "עדשים ירוקות"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 353, protein_g: 25, fat_g: 1.1, carbs_g: 60 },
  },
  {
    id: "ing.chickpeas",
    name_he: "גרגירי חומוס יבשים",
    aliases: ["חומוס יבש", "גרגירי חומוס"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 364, protein_g: 19, fat_g: 6, carbs_g: 61 },
  },
  {
    // משומרת ומסוננת — הערך התזונתי שונה מהותית מיבשה, ולכן מצרך נפרד.
    id: "ing.canned_beans",
    name_he: "שעועית אדומה משומרת",
    aliases: ["שעועית משומרת", "שעועית אדומה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 127, protein_g: 8.7, fat_g: 0.5, carbs_g: 22.8 },
  },
  {
    id: "ing.canned_tuna",
    name_he: "טונה בשימורים",
    aliases: ["טונה", "קופסת טונה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 186, protein_g: 25.5, fat_g: 8.2, carbs_g: 0 },
  },
  {
    id: "ing.corn",
    name_he: "תירס משומר",
    aliases: ["תירס", "קופסת תירס"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 86, protein_g: 3.2, fat_g: 1.2, carbs_g: 19 },
  },
  {
    id: "ing.breadcrumbs",
    name_he: "פירורי לחם",
    aliases: ["פירורי ציפוי"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 395, protein_g: 13, fat_g: 5.3, carbs_g: 72 },
  },
  {
    id: "ing.bread",
    name_he: "לחם פרוס",
    aliases: ["לחם", "פרוסת לחם"],
    base_unit: "g",
    unit_weight_g: 30,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 265, protein_g: 9, fat_g: 3.2, carbs_g: 49 },
  },
  {
    id: "ing.pita",
    name_he: "פיתה",
    aliases: ["פיתות"],
    base_unit: "g",
    unit_weight_g: 70,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 275, protein_g: 9, fat_g: 1.2, carbs_g: 55 },
  },
  {
    id: "ing.flour",
    name_he: "קמח לבן",
    aliases: ["קמח"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 364, protein_g: 10, fat_g: 1, carbs_g: 76 },
  },
  {
    id: "ing.yeast",
    name_he: "שמרים יבשים",
    aliases: ["שמרים"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 325, protein_g: 40, fat_g: 7.6, carbs_g: 41 },
  },

  {
    id: "ing.brown_rice",
    name_he: "אורז מלא",
    aliases: ["אורז חום"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 367, protein_g: 7.5, fat_g: 2.7, carbs_g: 76 },
  },
  {
    id: "ing.ramen_noodles",
    name_he: "אטריות ראמן",
    aliases: ["נודלס", "אטריות ביצים"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 356, protein_g: 10, fat_g: 1.5, carbs_g: 74 },
  },
  {
    id: "ing.baguette",
    name_he: "באגט",
    aliases: [],
    base_unit: "g",
    unit_weight_g: 250,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 274, protein_g: 9, fat_g: 1.3, carbs_g: 55 },
  },
  {
    id: "ing.challah",
    name_he: "חלה",
    aliases: ["לחם מתוק"],
    base_unit: "g",
    unit_weight_g: 500,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 290, protein_g: 8.5, fat_g: 6, carbs_g: 50 },
  },
  {
    id: "ing.frena",
    name_he: "פרנה",
    aliases: ["לחם מרוקאי"],
    base_unit: "g",
    unit_weight_g: 120,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 280, protein_g: 8, fat_g: 4, carbs_g: 52 },
  },
  {
    id: "ing.roll",
    name_he: "לחמנייה",
    aliases: ["לחמניות"],
    base_unit: "g",
    unit_weight_g: 70,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 280, protein_g: 9, fat_g: 4, carbs_g: 50 },
  },
  {
    id: "ing.whole_bread",
    name_he: "לחם מלא",
    aliases: ["לחם חיטה מלאה"],
    base_unit: "g",
    unit_weight_g: 30,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 247, protein_g: 13, fat_g: 3.4, carbs_g: 41 },
  },
  {
    id: "ing.spelt_bread",
    name_he: "לחם כוסמין",
    aliases: ["כוסמין"],
    base_unit: "g",
    unit_weight_g: 30,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 255, protein_g: 11, fat_g: 3, carbs_g: 45 },
  },
  {
    id: "ing.rye_bread",
    name_he: "לחם שיפון",
    aliases: ["שיפון"],
    base_unit: "g",
    unit_weight_g: 30,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 259, protein_g: 8.5, fat_g: 3.3, carbs_g: 48 },
  },

  /* ---------- מזווה ----------
     pantry_staple מסמן "תמיד יש בבית" ומוריד את המצרך מרשימת הקניות.
     שמור לתבלינים ולשמן בלבד: כל דבר שבאמת נגמר ושצריך לזכור לקנות
     חייב להישאר ברשימה, אחרת ההשמטה השקטה היא בדיוק סוג הטעות
     שהמנוע נבנה כדי למנוע. */
  {
    id: "ing.olive_oil",
    name_he: "שמן זית",
    aliases: ["שמן"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: 0.91,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 884, protein_g: 0, fat_g: 100, carbs_g: 0 },
  },
  {
    id: "ing.salt",
    name_he: "מלח",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 0, protein_g: 0, fat_g: 0, carbs_g: 0 },
  },
  {
    id: "ing.black_pepper",
    name_he: "פלפל שחור",
    aliases: ["פלפל שחור טחון"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 251, protein_g: 10, fat_g: 3.3, carbs_g: 64 },
  },
  {
    id: "ing.paprika",
    name_he: "פפריקה",
    aliases: ["פפריקה מתוקה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 282, protein_g: 14, fat_g: 13, carbs_g: 54 },
  },
  {
    id: "ing.cumin",
    name_he: "כמון",
    aliases: ["כמון טחון"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 375, protein_g: 18, fat_g: 22, carbs_g: 44 },
  },
  {
    id: "ing.tomato_paste",
    name_he: "רסק עגבניות",
    aliases: ["רסק", "רסק עגבניות מרוכז"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 82, protein_g: 4.3, fat_g: 0.5, carbs_g: 19 },
  },
  {
    id: "ing.tahini",
    name_he: "טחינה גולמית",
    aliases: ["טחינה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 595, protein_g: 17, fat_g: 53, carbs_g: 21 },
  },
  {
    id: "ing.mayonnaise",
    name_he: "מיונז",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 680, protein_g: 1, fat_g: 75, carbs_g: 1.5 },
  },
  {
    id: "ing.honey",
    name_he: "דבש",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 304, protein_g: 0.3, fat_g: 0, carbs_g: 82 },
  },
  {
    id: "ing.sugar",
    name_he: "סוכר",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 387, protein_g: 0, fat_g: 0, carbs_g: 100 },
  },

  {
    id: "ing.soy_sauce",
    name_he: "רוטב סויה",
    aliases: ["סויה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: 1.1,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 53, protein_g: 8, fat_g: 0.1, carbs_g: 4.9 },
  },
  {
    id: "ing.sesame_oil",
    name_he: "שמן שומשום",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: 0.92,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 884, protein_g: 0, fat_g: 100, carbs_g: 0 },
  },
  {
    id: "ing.turmeric",
    name_he: "כורכום",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 312, protein_g: 9.7, fat_g: 3.3, carbs_g: 67 },
  },
  {
    id: "ing.shawarma_spice",
    name_he: "תערובת שווארמה",
    aliases: ["תבלין שווארמה", "בהרט"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 300, protein_g: 11, fat_g: 8, carbs_g: 50 },
  },
  {
    id: "ing.corn_starch",
    name_he: "קורנפלור",
    aliases: ["עמילן תירס"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 381, protein_g: 0.3, fat_g: 0.1, carbs_g: 91 },
  },
  {
    id: "ing.olives",
    name_he: "זיתים",
    aliases: ["זית"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 145, protein_g: 1, fat_g: 15, carbs_g: 3.8 },
  },
  {
    id: "ing.sun_dried_tomato",
    name_he: "עגבניות מיובשות",
    aliases: ["עגבניה מיובשת"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 213, protein_g: 5.1, fat_g: 14, carbs_g: 23 },
  },

  /* ---------- נשנושים ומשקאות ----------

     נשנוש נמדד כמעט תמיד ביחידות ("תפוח אחד") ולא במשקל, ולכן לכל
     פריט כאן יש unit_weight_g. בלעדיו הוא היה נופל למסלול הידני
     בדיוק במקום שבו הרווח כולו הוא הוספה בהקשה אחת.

     במשקאות base_unit הוא ml, ולכן nutrition_per_100 הוא לכל 100
     מ"ל — לא לכל 100 גרם.

     שים לב ש-unit_weight_g הוא *משקל* גם במשקה, ולכן הוא נגזר מהנפח
     כפול הצפיפות ולא שווה לו: פחית קולה של 330 מ"ל שוקלת 343 גרם.
     המרת "יחידה אחת" עוברת דרך הגרמים חזרה למ"ל, וערך שהושאר כנפח
     היה מחזיר 317 מ"ל לפחית — טעות של 4% בכל הזנה. */
  {
    id: "ing.apple",
    name_he: "תפוח",
    aliases: ["תפוחים", "תפוח עץ"],
    base_unit: "g",
    unit_weight_g: 180,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 52, protein_g: 0.3, fat_g: 0.2, carbs_g: 14 },
  },
  {
    id: "ing.cottage",
    name_he: "קוטג'",
    aliases: ["גבינת קוטג'"],
    base_unit: "g",
    unit_weight_g: 250,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 98, protein_g: 11, fat_g: 4.3, carbs_g: 3.4 },
  },
  {
    id: "ing.almonds",
    name_he: "שקדים",
    aliases: ["שקד"],
    base_unit: "g",
    unit_weight_g: 30,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 579, protein_g: 21, fat_g: 50, carbs_g: 22 },
  },
  {
    id: "ing.dark_chocolate",
    name_he: "שוקולד מריר",
    aliases: ["שוקולד"],
    base_unit: "g",
    unit_weight_g: 25,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 546, protein_g: 6, fat_g: 31, carbs_g: 61 },
  },
  {
    id: "ing.pretzels",
    name_he: "בייגלה",
    aliases: ["בייגלה מלוח"],
    base_unit: "g",
    unit_weight_g: 30,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 380, protein_g: 10, fat_g: 3, carbs_g: 79 },
  },
  {
    id: "ing.water",
    name_he: "מים",
    aliases: ["כוס מים"],
    base_unit: "ml",
    unit_weight_g: 250,
    density_g_per_ml: 1,
    shelf: "drinks",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 0, protein_g: 0, fat_g: 0, carbs_g: 0 },
  },
  {
    id: "ing.coffee_black",
    name_he: "קפה שחור",
    aliases: ["קפה"],
    base_unit: "ml",
    unit_weight_g: 200,
    density_g_per_ml: 1,
    shelf: "drinks",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 1, protein_g: 0.1, fat_g: 0, carbs_g: 0 },
  },
  {
    id: "ing.orange_juice",
    name_he: "מיץ תפוזים",
    aliases: ["מיץ"],
    base_unit: "ml",
    unit_weight_g: 262,
    density_g_per_ml: 1.05,
    shelf: "drinks",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 45, protein_g: 0.7, fat_g: 0.2, carbs_g: 10 },
  },
  {
    id: "ing.cola",
    name_he: "קולה",
    aliases: ["משקה מוגז"],
    base_unit: "ml",
    unit_weight_g: 343,
    density_g_per_ml: 1.04,
    shelf: "drinks",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 42, protein_g: 0, fat_g: 0, carbs_g: 10.6 },
  },
  {
    id: "ing.beer",
    name_he: "בירה",
    aliases: [],
    base_unit: "ml",
    unit_weight_g: 333,
    density_g_per_ml: 1.01,
    shelf: "drinks",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 43, protein_g: 0.5, fat_g: 0, carbs_g: 3.6 },
  },

  /* ---------- רכיבי הרכבה ----------
     המצרכים שהמנות המודולריות נשענות עליהן. חסה וקוסקוס הם רכיבי
     בסיס, וחומוס מוכן וחמאה נקנים מוכנים ולכן הם מצרך אחד ולא מתכון. */
  {
    // ראש חסה נע בין 300 ל-700 גרם, ולכן unit_weight_g נשאר null:
    // "חסה אחת" תגיע לרשימה כפריט להכרעה במקום כמספר מומצא.
    id: "ing.lettuce",
    name_he: "חסה",
    aliases: ["עלי חסה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 15, protein_g: 1.4, fat_g: 0.2, carbs_g: 2.9 },
  },
  {
    id: "ing.couscous",
    name_he: "קוסקוס",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 376, protein_g: 12.8, fat_g: 0.6, carbs_g: 77 },
  },
  {
    id: "ing.hummus",
    name_he: "חומוס מוכן",
    aliases: ["חומוס"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "chilled",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 166, protein_g: 8, fat_g: 10, carbs_g: 14 },
  },
  {
    id: "ing.butter",
    name_he: "חמאה",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 717, protein_g: 0.9, fat_g: 81, carbs_g: 0.1 },
  },
  {
    id: "ing.tofu",
    name_he: "טופו",
    aliases: ["טופו קשה"],
    base_unit: "g",
    unit_weight_g: 300,
    density_g_per_ml: null,
    shelf: "chilled",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 144, protein_g: 15.8, fat_g: 8.7, carbs_g: 2.8 },
  },
  {
    id: "ing.pesto",
    name_he: "פסטו",
    aliases: ["רוטב פסטו"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "chilled",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 450, protein_g: 5, fat_g: 45, carbs_g: 6 },
  },
];

/* כמויות המנה הן תמיד למנה בודדת אחת. ההכפלה קורה רק בשכבת התוכנית.

   ── למה הקטלוג בגודל הזה ────────────────────────────────────────────
   גרסה קודמת נזרעה בשלוש מנות, וזה נראה מספיק כי בכל מקרה מוסיפים
   מנות בעצמך. בפועל זה שבר שני דברים: התקנה טרייה נחתה על מתכנן שאין
   בו מה לתכנן, והבלוק "לא בישלנו מזמן" — שמוסתר מתחת לשבע מנות —
   מעולם לא רץ אצל מי שלא הקליד ידנית עוד ארבע. קטלוג פותח צריך להיות
   גדול מספיק כדי שהשבוע הראשון יתוכנן בלי הקלדה. */
export const DISHES = [
  {
    id: "dish.schnitzel_chips",
    name_he: "שניצל וצ'יפס",
    role: "main",
    kosher: "meat",
    effort: "medium",
    time_min: 35,
    ingredients: [
      { ingredient_id: "ing.chicken_breast", qty: 150, unit: "g" },
      { ingredient_id: "ing.egg", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.breadcrumbs", qty: 40, unit: "g" },
      { ingredient_id: "ing.potato", qty: 250, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 20, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["לצפות את השניצל מראש"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.rice_veg",
    name_he: "אורז עם בצל ועגבניות",
    role: "main",
    kosher: "parve",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.rice", qty: 80, unit: "g" },
      { ingredient_id: "ing.onion", qty: 2, unit: "unit" },
      { ingredient_id: "ing.tomato", qty: 2, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.veg_omelette",
    name_he: "חביתת ירק עם יוגורט",
    role: "main",
    kosher: "dairy",
    effort: "low",
    time_min: 15,
    ingredients: [
      { ingredient_id: "ing.egg", qty: 2, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 150, unit: "g" },
      { ingredient_id: "ing.tomato", qty: 1, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
      { ingredient_id: "ing.yogurt", qty: 1, unit: "unit" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.shakshuka",
    name_he: "שקשוקה",
    kosher: "parve",
    effort: "low",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.egg", qty: 2, unit: "unit" },
      { ingredient_id: "ing.tomato", qty: 2, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.bell_pepper", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.tomato_paste", qty: 20, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.paprika", qty: 3, unit: "g" },
      { ingredient_id: "ing.cumin", qty: 2, unit: "g" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick", "breakfast"],
    macros_override: null,
  },
  {
    id: "dish.israeli_salad_cheese",
    name_he: "סלט ירקות עם גבינה בולגרית",
    kosher: "dairy",
    effort: "low",
    time_min: 10,
    ingredients: [
      { ingredient_id: "ing.cucumber", qty: 1.5, unit: "unit" },
      { ingredient_id: "ing.tomato", qty: 1.5, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 0.25, unit: "unit" },
      { ingredient_id: "ing.parsley", qty: 10, unit: "g" },
      { ingredient_id: "ing.bulgarian_cheese", qty: 50, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.lemon", qty: 0.25, unit: "unit" },
      { ingredient_id: "ing.salt", qty: 1, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick", "breakfast"],
    macros_override: null,
  },
  {
    id: "dish.cheese_toast",
    name_he: "טוסט גבינה וירקות",
    kosher: "dairy",
    effort: "low",
    time_min: 8,
    ingredients: [
      { ingredient_id: "ing.bread", qty: 2, unit: "unit" },
      { ingredient_id: "ing.yellow_cheese", qty: 2, unit: "unit" },
      { ingredient_id: "ing.tomato", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 5, unit: "ml" },
    ],
    prep_ahead: [],
    tags: ["quick", "breakfast"],
    macros_override: null,
  },
  {
    id: "dish.oatmeal",
    name_he: "דייסת שיבולת שועל",
    kosher: "dairy",
    effort: "low",
    time_min: 10,
    ingredients: [
      { ingredient_id: "ing.oats", qty: 50, unit: "g" },
      { ingredient_id: "ing.milk", qty: 250, unit: "ml" },
      { ingredient_id: "ing.banana", qty: 1, unit: "unit" },
      { ingredient_id: "ing.honey", qty: 10, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick", "breakfast"],
    macros_override: null,
  },
  {
    id: "dish.roast_chicken_potatoes",
    name_he: "עוף בתנור עם תפוחי אדמה",
    kosher: "meat",
    effort: "low",
    time_min: 70,
    ingredients: [
      { ingredient_id: "ing.chicken_thigh", qty: 200, unit: "g" },
      { ingredient_id: "ing.potato", qty: 250, unit: "g" },
      { ingredient_id: "ing.onion", qty: 1, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.paprika", qty: 4, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
      { ingredient_id: "ing.black_pepper", qty: 1, unit: "g" },
    ],
    prep_ahead: ["לתבל את העוף מראש ולהשאיר במקרר"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.meatballs_tomato",
    name_he: "קציצות בקר ברוטב עגבניות",
    kosher: "meat",
    effort: "medium",
    time_min: 45,
    ingredients: [
      { ingredient_id: "ing.ground_beef", qty: 150, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.egg", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.breadcrumbs", qty: 25, unit: "g" },
      { ingredient_id: "ing.tomato_paste", qty: 40, unit: "g" },
      { ingredient_id: "ing.tomato", qty: 1, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
      { ingredient_id: "ing.black_pepper", qty: 1, unit: "g" },
    ],
    prep_ahead: ["לגלגל את הקציצות מראש"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.pasta_bolognese",
    name_he: "פסטה בולונז",
    kosher: "meat",
    effort: "medium",
    time_min: 40,
    ingredients: [
      { ingredient_id: "ing.pasta", qty: 100, unit: "g" },
      { ingredient_id: "ing.ground_beef", qty: 120, unit: "g" },
      { ingredient_id: "ing.tomato_paste", qty: 50, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["הרוטב יוצא טוב יותר כשמכינים אותו יום קודם"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.chicken_soup",
    name_he: "מרק עוף עם אטריות",
    kosher: "meat",
    effort: "medium",
    time_min: 60,
    ingredients: [
      { ingredient_id: "ing.chicken_thigh", qty: 150, unit: "g" },
      { ingredient_id: "ing.carrot", qty: 1, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.potato", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.soup_noodles", qty: 40, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
      { ingredient_id: "ing.black_pepper", qty: 1, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.shawarma_pita",
    name_he: "שווארמה ביתית בפיתה",
    kosher: "meat",
    effort: "medium",
    time_min: 30,
    ingredients: [
      { ingredient_id: "ing.chicken_thigh", qty: 180, unit: "g" },
      { ingredient_id: "ing.pita", qty: 1, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.tahini", qty: 30, unit: "g" },
      { ingredient_id: "ing.cucumber", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.tomato", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.cumin", qty: 3, unit: "g" },
      { ingredient_id: "ing.paprika", qty: 2, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "לפרוס את ירך העוף לרצועות ולהשרות בכמון, פפריקה ושמן זית.",
      "לצרוב במחבת לוהטת בשתי מנות, עד שהקצוות מתקרמלים.",
      "לחמם את הפיתה על מחבת יבשה.",
      "למרוח טחינה בתוך הפיתה לפני הבשר, לא מעליו. כך היא לא נשפכת החוצה.",
    ],
    prep_ahead: ["לתבל את העוף בערב הקודם"],
    tags: [],
    macros_override: null,
  },
  {
    id: "dish.beef_chili",
    name_he: "צ'ילי בשר ושעועית",
    kosher: "meat",
    effort: "medium",
    time_min: 50,
    ingredients: [
      { ingredient_id: "ing.ground_beef", qty: 120, unit: "g" },
      { ingredient_id: "ing.canned_beans", qty: 150, unit: "g" },
      { ingredient_id: "ing.tomato_paste", qty: 40, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.bell_pepper", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.cumin", qty: 3, unit: "g" },
      { ingredient_id: "ing.paprika", qty: 3, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.mejadra",
    name_he: "מג'דרה",
    kosher: "parve",
    effort: "low",
    time_min: 40,
    ingredients: [
      { ingredient_id: "ing.rice", qty: 70, unit: "g" },
      { ingredient_id: "ing.lentils", qty: 50, unit: "g" },
      { ingredient_id: "ing.onion", qty: 1.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 20, unit: "ml" },
      { ingredient_id: "ing.cumin", qty: 3, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["אפשר לטגן את הבצל מראש"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.pasta_cream",
    name_he: "פסטה ברוטב עגבניות ושמנת",
    kosher: "dairy",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.pasta", qty: 100, unit: "g" },
      { ingredient_id: "ing.tomato_paste", qty: 40, unit: "g" },
      { ingredient_id: "ing.cream", qty: 60, unit: "ml" },
      { ingredient_id: "ing.parmesan", qty: 15, unit: "g" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.homemade_pizza",
    name_he: "פיצה ביתית",
    kosher: "dairy",
    effort: "high",
    time_min: 60,
    ingredients: [
      { ingredient_id: "ing.flour", qty: 120, unit: "g" },
      { ingredient_id: "ing.yeast", qty: 3, unit: "g" },
      { ingredient_id: "ing.mozzarella", qty: 80, unit: "g" },
      { ingredient_id: "ing.tomato_paste", qty: 50, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.sugar", qty: 3, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["להכין את הבצק מראש ולתת לו לתפוח במקרר"],
    tags: [],
    macros_override: null,
  },
  {
    id: "dish.quinoa_salad",
    name_he: "סלט קינואה עם ירקות",
    kosher: "parve",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.quinoa", qty: 60, unit: "g" },
      { ingredient_id: "ing.cucumber", qty: 1, unit: "unit" },
      { ingredient_id: "ing.tomato", qty: 1, unit: "unit" },
      { ingredient_id: "ing.parsley", qty: 15, unit: "g" },
      { ingredient_id: "ing.lemon", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: ["אפשר לבשל את הקינואה מראש"],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.hummus",
    name_he: "חומוס ביתי",
    kosher: "parve",
    effort: "medium",
    time_min: 40,
    ingredients: [
      { ingredient_id: "ing.chickpeas", qty: 80, unit: "g" },
      { ingredient_id: "ing.tahini", qty: 40, unit: "g" },
      { ingredient_id: "ing.lemon", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.garlic", qty: 1, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.cumin", qty: 2, unit: "g" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "להשרות את הגרגירים בלילה במים.",
      "לבשל שעה וחצי עד שהגרגיר נמעך בין שתי אצבעות בלי התנגדות. פחות מזה נותן חומוס גרגירי.",
      "לטחון חם עם טחינה גולמית, לימון, שום ומלח. חומוס קר לא נהיה חלק.",
      "להוסיף ממי הבישול כף אחר כף, עד המרקם שרוצים.",
    ],
    prep_ahead: ["להשרות את הגרגירים מלילה קודם"],
    tags: [],
    macros_override: null,
  },
  {
    id: "dish.lentil_soup",
    name_he: "מרק עדשים",
    kosher: "parve",
    effort: "low",
    time_min: 45,
    ingredients: [
      { ingredient_id: "ing.lentils", qty: 70, unit: "g" },
      { ingredient_id: "ing.carrot", qty: 1, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.potato", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.cumin", qty: 3, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    steps: [
      "לטגן בצל וגזר קצוצים בשמן זית עד שהבצל שקוף.",
      "להוסיף עדשים ותפוח אדמה, לכסות במים ולהביא לרתיחה.",
      "לבשל 30 דקות על אש נמוכה, עד שהעדשים מתפרקות.",
      "לתבל בכמון ומלח רק בסוף. כמון שנכנס בהתחלה מאבד את הריח.",
      "לטחון חלקית במוט בלנדר לסמיכות, או להשאיר גס.",
    ],
    prep_ahead: [],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.pasta_tomato_garlic",
    name_he: "פסטה ברוטב עגבניות ושום",
    kosher: "parve",
    effort: "low",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.pasta", qty: 100, unit: "g" },
      { ingredient_id: "ing.tomato_paste", qty: 50, unit: "g" },
      { ingredient_id: "ing.tomato", qty: 1, unit: "unit" },
      { ingredient_id: "ing.garlic", qty: 3, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.roasted_veg",
    // ירקות בתנור הם תוספת ירק, ולכן הם מרכיבים ולא מוגשים לבד.
    role: "veg",
    name_he: "ירקות בתנור",
    kosher: "parve",
    effort: "low",
    time_min: 45,
    ingredients: [
      { ingredient_id: "ing.sweet_potato", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.potato", qty: 1, unit: "unit" },
      { ingredient_id: "ing.carrot", qty: 1, unit: "unit" },
      { ingredient_id: "ing.zucchini", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 20, unit: "ml" },
      { ingredient_id: "ing.paprika", qty: 3, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["אפשר לחתוך את הירקות מראש"],
    tags: [],
    macros_override: null,
  },
  {
    id: "dish.baked_salmon",
    // סלמון אפוי הוא חלבון על הצלחת, לא ארוחה שלמה.
    role: "protein",
    name_he: "סלמון בתנור עם לימון",
    kosher: "parve",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.salmon", qty: 180, unit: "g" },
      { ingredient_id: "ing.lemon", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.garlic", qty: 1, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
      { ingredient_id: "ing.black_pepper", qty: 1, unit: "g" },
    ],
    steps: [
      "לחמם תנור ל-200 מעלות.",
      "לייבש את הפילה ולשפשף בשמן זית, מלח ופלפל.",
      "לאפות 12 עד 15 דקות לפי העובי. הסלמון מוכן כשהוא מתקלף בלחיצת מזלג ועדיין ורוד במרכז.",
      "לסחוט לימון בסוף ולא בהתחלה. חומצה שנכנסת מוקדם מבשלת את פני הדג.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.tuna_salad",
    name_he: "סלט טונה",
    kosher: "parve",
    effort: "low",
    time_min: 10,
    ingredients: [
      { ingredient_id: "ing.canned_tuna", qty: 80, unit: "g" },
      { ingredient_id: "ing.mayonnaise", qty: 20, unit: "g" },
      { ingredient_id: "ing.cucumber", qty: 1, unit: "unit" },
      { ingredient_id: "ing.corn", qty: 40, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.25, unit: "unit" },
      { ingredient_id: "ing.lemon", qty: 0.25, unit: "unit" },
      { ingredient_id: "ing.salt", qty: 1, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.ptitim_veg",
    name_he: "פתיתים עם ירקות",
    kosher: "parve",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.ptitim", qty: 90, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.bell_pepper", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.carrot", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick", "comfort"],
    macros_override: null,
  },
  {
    id: "dish.fried_rice_egg",
    name_he: "אורז מוקפץ עם ירקות וביצה",
    kosher: "parve",
    effort: "low",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.rice", qty: 80, unit: "g" },
      { ingredient_id: "ing.egg", qty: 1.5, unit: "unit" },
      { ingredient_id: "ing.carrot", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.bell_pepper", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: ["יוצא הכי טוב עם אורז מאתמול"],
    tags: ["quick"],
    macros_override: null,
  },

  {
    id: "dish.stuffed_peppers",
    name_he: "פלפל ממולא",
    role: "main",
    kosher: "meat",
    effort: "medium",
    time_min: 70,
    ingredients: [
      { ingredient_id: "ing.bell_pepper", qty: 2, unit: "unit" },
      { ingredient_id: "ing.ground_beef", qty: 120, unit: "g" },
      { ingredient_id: "ing.rice", qty: 40, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.tomato_paste", qty: 40, unit: "g" },
      { ingredient_id: "ing.parsley", qty: 10, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.cumin", qty: 2, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    steps: [
      "לחתוך כובעים מהפלפלים ולנקות את הגרעינים. לשמור את הכובעים.",
      "לערבב בשר טחון, אורז לא מבושל, בצל קצוץ, פטרוזיליה, כמון ומלח.",
      "למלא שלושה רבעים בלבד. האורז תופח ומילוי מלא מפוצץ את הפלפל.",
      "לסדר צפוף בסיר, לצקת רוטב עגבניות ומים עד שני שליש מגובה הפלפלים.",
      "לבשל מכוסה על אש נמוכה 50 דקות, בלי לערבב.",
    ],
    prep_ahead: ["להכין את המילוי מראש"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.masabacha",
    name_he: "מסבחה",
    role: "main",
    kosher: "parve",
    effort: "medium",
    time_min: 90,
    ingredients: [
      { ingredient_id: "ing.chickpeas", qty: 100, unit: "g" },
      { ingredient_id: "ing.tahini", qty: 40, unit: "g" },
      { ingredient_id: "ing.lemon", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.cumin", qty: 2, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.parsley", qty: 10, unit: "g" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "להשרות את הגרגירים בלילה, ולבשל עד שהם רכים מאוד. לשמור כוס ממי הבישול.",
      "לטחון שליש מהגרגירים עם טחינה, לימון ושום למחית.",
      "להחזיר את שאר הגרגירים שלמים לתוך המחית. זה כל ההבדל בין מסבחה לחומוס.",
      "לדלל במי הבישול למרקם נוזלי, ולתבל בכמון ומלח.",
      "להגיש חם, עם שמן זית ופטרוזיליה מעל.",
    ],
    prep_ahead: ["להשרות את הגרגירים בלילה"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.ramen",
    name_he: "ראמן",
    role: "main",
    kosher: "meat",
    effort: "medium",
    time_min: 35,
    ingredients: [
      { ingredient_id: "ing.ramen_noodles", qty: 100, unit: "g" },
      { ingredient_id: "ing.egg", qty: 1, unit: "unit" },
      { ingredient_id: "ing.chicken_thigh", qty: 100, unit: "g" },
      { ingredient_id: "ing.mushroom", qty: 60, unit: "g" },
      { ingredient_id: "ing.scallion", qty: 20, unit: "g" },
      { ingredient_id: "ing.soy_sauce", qty: 30, unit: "ml" },
      { ingredient_id: "ing.sesame_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.ginger", qty: 5, unit: "g" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
    ],
    steps: [
      "לבשל ביצה 7 דקות בדיוק ולהעביר למי קרח. בזמן הזה החלמון נשאר נוזלי במרכז.",
      "להרתיח ציר עם ג'ינג'ר, שום, סויה ושמן שומשום, ולבשל בו את העוף 10 דקות.",
      "להוסיף פטריות לשתי הדקות האחרונות.",
      "לבשל את האטריות בסיר נפרד ולסנן. עמילן שנכנס לציר הופך אותו לעכור.",
      "להרכיב בקערה: אטריות, ציר רותח, עוף, חצי ביצה ובצל ירוק.",
    ],
    prep_ahead: ["לבשל את הביצים מראש"],
    tags: ["comfort"],
    macros_override: null,
  },

  /* ---------- רכיבים להרכבה ----------

     14 הרכיבים שהופכים משבצת מ"מנה שנבחרה" ל"ארוחה שהורכבה": חלבון,
     תוספת, ירק ומטבל. 25 מנות הזרע שמעליהן נשארו main — "שניצל
     וצ'יפס" בהקשה אחת הוא קיצור אמיתי לערב שלא רוצים להרכיב בו כלום,
     ומנה בלי role נופלת ל-main ממילא (ראה dishRole ב-compose.js). */
  {
    id: "dish.schnitzel",
    name_he: "שניצל עוף",
    role: "protein",
    kosher: "meat",
    effort: "medium",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.chicken_breast", qty: 150, unit: "g" },
      { ingredient_id: "ing.egg", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.breadcrumbs", qty: 40, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    steps: [
      "לפרוס את החזה לפילטים דקים ולהשטיח קלות.",
      "לטבול בביצה טרופה ואז בפירורים, וללחוץ את הפירורים ביד. ציפוי שלא נלחץ נופל בטיגון.",
      "לטגן בשמן בעומק חצי סנטימטר, 3 דקות לכל צד עד זהוב.",
      "לנקז על רשת ולא על נייר. נייר מאדה את התחתית ומרכך את הציפוי.",
    ],
    prep_ahead: ["לצפות את השניצל מראש"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.grilled_chicken",
    name_he: "חזה עוף בגריל",
    role: "protein",
    kosher: "meat",
    effort: "low",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.chicken_breast", qty: 180, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    steps: [
      "לפרוס את החזה לרוחב לשני פילטים, או להשטיח במכה. חזה שלם מתייבש מבחוץ לפני שהמרכז מוכן.",
      "לתבל בשמן זית ומלח, ולתת לעמוד 10 דקות בטמפרטורת החדר.",
      "לצרוב על גריל לוהט 4 דקות לכל צד בלי להזיז.",
      "להוציא ולתת לנוח 5 דקות לפני חיתוך.",
    ],
    prep_ahead: ["להשרות את העוף מראש"],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.meatballs",
    name_he: "קציצות בקר",
    role: "protein",
    kosher: "meat",
    effort: "medium",
    time_min: 35,
    ingredients: [
      { ingredient_id: "ing.ground_beef", qty: 150, unit: "g" },
      { ingredient_id: "ing.onion", qty: 40, unit: "g" },
      { ingredient_id: "ing.egg", qty: 0.25, unit: "unit" },
      { ingredient_id: "ing.breadcrumbs", qty: 20, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    steps: [
      "לקצוץ בצל דק מאוד ולערבב עם הבשר, הביצה והפירורים.",
      "ללוש עד שהתערובת נדבקת, ולקרר 20 דקות. קציצה קרה שומרת על הצורה.",
      "לגלגל בידיים רטובות ולצרוב במחבת מכל הצדדים.",
    ],
    prep_ahead: ["לגלגל את הקציצות מראש"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.omelette",
    name_he: "חביתה",
    role: "protein",
    kosher: "parve",
    effort: "low",
    time_min: 10,
    ingredients: [
      { ingredient_id: "ing.egg", qty: 2, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 5, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 1, unit: "g" },
    ],
    steps: [
      "לטרוף את הביצים עם מלח עד שהן אחידות בצבע.",
      "לחמם מחבת על אש בינונית־נמוכה. חביתה על אש גבוהה נהיית גומי.",
      "לצקת, ולערבב בעדינות עד שהיא כמעט מוצקה. היא מסיימת להתבשל בצלחת.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.oven_chips",
    name_he: "צ'יפס בתנור",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 30,
    ingredients: [
      { ingredient_id: "ing.potato", qty: 250, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    steps: [
      "לחתוך לרצועות אחידות ולהשרות 20 דקות במים קרים. זה מוציא עמילן והצ'יפס יוצא פריך.",
      "לייבש היטב ולערבב בשמן זית ומלח.",
      "לאפות 220 מעלות 25 דקות, ולהפוך פעם אחת באמצע.",
    ],
    prep_ahead: ["לחתוך את תפוחי האדמה מראש"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.white_rice",
    name_he: "אורז לבן",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.rice", qty: 80, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 5, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "לשטוף את האורז עד שהמים יוצאים צלולים.",
      "לבשל ביחס כוס אורז לכוס וחצי מים, 15 דקות מכוסה על אש נמוכה.",
      "לכבות ולתת לעמוד 10 דקות מכוסה. פתיחה מוקדמת משאירה את השכבה העליונה קשה.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.mashed_potato",
    name_he: "פירה",
    role: "side",
    kosher: "dairy",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.potato", qty: 250, unit: "g" },
      { ingredient_id: "ing.butter", qty: 15, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    steps: [
      "לבשל את תפוחי האדמה שלמים בקליפה. חתוכים סופגים מים והפירה יוצא מימי.",
      "לקלף חם ולמעוך במועך, לא בבלנדר. בלנדר הופך עמילן לדבק.",
      "לערבב עם חמאה ומלח.",
    ],
    prep_ahead: [],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.pasta_plain",
    name_he: "פסטה",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 15,
    ingredients: [
      { ingredient_id: "ing.pasta", qty: 90, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "לבשל במים מלוחים, דקה פחות ממה שכתוב על החבילה.",
      "לסנן ולערבב מיד בשמן זית, כדי שלא תידבק.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.couscous_side",
    name_he: "קוסקוס",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 10,
    ingredients: [
      { ingredient_id: "ing.couscous", qty: 80, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "להרתיח מים ביחס אחד לאחד עם הקוסקוס, ולערבב שמן זית ומלח.",
      "לצקת על הקוסקוס, לכסות, ולתת לעמוד 8 דקות.",
      "לנפח במזלג.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.warm_pita",
    name_he: "פיתה חמה",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 5,
    ingredients: [{ ingredient_id: "ing.pita", qty: 1, unit: "unit" }],
    steps: ["לחמם על מחבת יבשה או ישירות על הלהבה, 30 שניות לכל צד."],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.israeli_salad",
    name_he: "סלט ישראלי",
    role: "veg",
    kosher: "parve",
    effort: "low",
    time_min: 10,
    ingredients: [
      { ingredient_id: "ing.tomato", qty: 120, unit: "g" },
      { ingredient_id: "ing.cucumber", qty: 100, unit: "g" },
      { ingredient_id: "ing.onion", qty: 25, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 1, unit: "g" },
    ],
    steps: [
      "לחתוך עגבנייה ומלפפון לקוביות באותו גודל. אחידות היא כל ההבדל בסלט הזה.",
      "לקצוץ בצל דק ולהוסיף.",
      "לתבל בשמן זית, מלח ולימון רק לפני ההגשה. סלט מתובל מראש מוציא מים.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.green_salad",
    name_he: "סלט עלים",
    role: "veg",
    kosher: "parve",
    effort: "low",
    time_min: 5,
    ingredients: [
      { ingredient_id: "ing.lettuce", qty: 60, unit: "g" },
      { ingredient_id: "ing.cucumber", qty: 60, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 1, unit: "g" },
    ],
    steps: [
      "לשטוף ולייבש את העלים היטב. עלה רטוב דוחה את הרוטב.",
      "לתבל בשמן זית, מלח ולימון ממש לפני ההגשה.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.tahini_sauce",
    name_he: "טחינה",
    role: "dip",
    kosher: "parve",
    effort: "low",
    time_min: 5,
    ingredients: [
      { ingredient_id: "ing.tahini", qty: 30, unit: "g" },
      { ingredient_id: "ing.salt", qty: 1, unit: "g" },
    ],
    steps: [
      "לערבב טחינה גולמית עם מים קרים בהדרגה. היא תתפוס ותתקשה — זה תקין, להמשיך לערבב.",
      "להוסיף מים עד שהיא נשפכת מהכף בקו רציף.",
      "לתבל במלח ולימון.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.hummus_side",
    name_he: "חומוס",
    role: "dip",
    kosher: "parve",
    effort: "low",
    time_min: 5,
    ingredients: [
      { ingredient_id: "ing.hummus", qty: 100, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 5, unit: "ml" },
    ],
    steps: ["להוציא לצלוחית, לעשות גומה במרכז עם גב הכף ולמלא בשמן זית."],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.stir_fry_tofu",
    name_he: "מוקפץ טופו",
    role: "protein",
    kosher: "parve",
    effort: "medium",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.tofu", qty: 200, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.bell_pepper", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.carrot", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.mushroom", qty: 60, unit: "g" },
      { ingredient_id: "ing.scallion", qty: 20, unit: "g" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.ginger", qty: 5, unit: "g" },
      { ingredient_id: "ing.soy_sauce", qty: 30, unit: "ml" },
      { ingredient_id: "ing.sesame_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.corn_starch", qty: 5, unit: "g" },
    ],
    steps: [
      "לסחוט את הטופו בין שתי מגבות נייר 10 דקות ולחתוך לקוביות. טופו רטוב מתאדה במחבת במקום להשחים.",
      "לחתוך בצל, פלפל, גזר ופטריות לרצועות באותו עובי — הכל נכנס למחבת ביחד.",
      "לטגן את הטופו בשמן שומשום על אש גבוהה עד זהוב מכל הצדדים, ולהוציא.",
      "להקפיץ את הירקות 4 דקות, הקשים קודם, ולערבב מעט.",
      "להחזיר את הטופו עם סויה, שום וג'ינג'ר, ולסמיך בקורנפלור מומס בכף מים.",
    ],
    prep_ahead: ["לסחוט ולחתוך את הטופו מראש"],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.stir_fry_chicken",
    name_he: "מוקפץ עוף",
    role: "protein",
    kosher: "meat",
    effort: "medium",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.chicken_breast", qty: 180, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.bell_pepper", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.carrot", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.mushroom", qty: 60, unit: "g" },
      { ingredient_id: "ing.scallion", qty: 20, unit: "g" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.ginger", qty: 5, unit: "g" },
      { ingredient_id: "ing.soy_sauce", qty: 30, unit: "ml" },
      { ingredient_id: "ing.sesame_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.corn_starch", qty: 5, unit: "g" },
    ],
    steps: [
      "לחתוך את החזה לרצועות דקות נגד כיוון הסיבים.",
      "לערבב עם כף סויה וקורנפלור ולהשהות 10 דקות. הציפוי הזה הוא מה ששומר את העוף רך.",
      "לצרוב במחבת לוהטת בשתי מנות. מחבת עמוסה מבשלת באדים במקום לצרוב.",
      "להוציא את העוף, ולהקפיץ את הירקות 4 דקות.",
      "להחזיר הכל עם שום, ג'ינג'ר ושמן שומשום, ולערבב דקה.",
    ],
    prep_ahead: ["לחתוך ולהשרות את העוף מראש"],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.stir_fry_beef",
    name_he: "מוקפץ בקר",
    role: "protein",
    kosher: "meat",
    effort: "medium",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.beef_strips", qty: 180, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.bell_pepper", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.carrot", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.mushroom", qty: 60, unit: "g" },
      { ingredient_id: "ing.scallion", qty: 20, unit: "g" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.ginger", qty: 5, unit: "g" },
      { ingredient_id: "ing.soy_sauce", qty: 30, unit: "ml" },
      { ingredient_id: "ing.sesame_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.corn_starch", qty: 5, unit: "g" },
    ],
    steps: [
      "לחתוך את הבקר לרצועות דקות נגד הסיבים ולייבש במגבת נייר.",
      "לצרוב במחבת לוהטת 90 שניות לכל צד ולהוציא. בקר שממשיך להתבשל עם הירקות מתקשה.",
      "להקפיץ את הירקות 4 דקות.",
      "להחזיר את הבקר עם סויה, שום וג'ינג'ר, ולסמיך בקורנפלור מומס.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.stir_fry_fish",
    name_he: "מוקפץ דג",
    role: "protein",
    kosher: "parve",
    effort: "medium",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.tilapia", qty: 180, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.bell_pepper", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.carrot", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.mushroom", qty: 60, unit: "g" },
      { ingredient_id: "ing.scallion", qty: 20, unit: "g" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.ginger", qty: 5, unit: "g" },
      { ingredient_id: "ing.soy_sauce", qty: 30, unit: "ml" },
      { ingredient_id: "ing.sesame_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.corn_starch", qty: 5, unit: "g" },
    ],
    steps: [
      "לחתוך את הדג לקוביות גדולות ולייבש היטב.",
      "להקפיץ את הירקות קודם ולהוציא. דג שמערבבים איתם מתפרק.",
      "לצרוב את הדג 2 דקות לכל צד בשמן שומשום, בלי לגעת בו בינתיים.",
      "להחזיר את הירקות, לתבל בסויה וג'ינג'ר, ולערבב בעדינות פעם אחת.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.baked_tilapia",
    name_he: "אמנון בתנור",
    role: "protein",
    kosher: "parve",
    effort: "low",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.tilapia", qty: 180, unit: "g" },
      { ingredient_id: "ing.lemon", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.paprika", qty: 2, unit: "g" },
      { ingredient_id: "ing.parsley", qty: 5, unit: "g" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "לחמם תנור ל-200 מעלות.",
      "לייבש את הפילה ולשפשף בשמן זית, שום כתוש, פפריקה ומלח.",
      "לאפות 12 דקות. אמנון דק ומתייבש מהר, ולכן עדיף לבדוק דקה מוקדם מדי.",
      "לסחוט לימון ולפזר פטרוזיליה קצוצה רק בסוף.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.moroccan_fish",
    name_he: "דג מרוקאי",
    role: "protein",
    kosher: "parve",
    effort: "medium",
    time_min: 40,
    ingredients: [
      { ingredient_id: "ing.tilapia", qty: 180, unit: "g" },
      { ingredient_id: "ing.bell_pepper", qty: 1, unit: "unit" },
      { ingredient_id: "ing.tomato", qty: 1, unit: "unit" },
      { ingredient_id: "ing.garlic", qty: 4, unit: "unit" },
      { ingredient_id: "ing.chickpeas", qty: 40, unit: "g" },
      { ingredient_id: "ing.cilantro", qty: 15, unit: "g" },
      { ingredient_id: "ing.hot_pepper", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.paprika", qty: 5, unit: "g" },
      { ingredient_id: "ing.turmeric", qty: 2, unit: "g" },
      { ingredient_id: "ing.cumin", qty: 2, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 20, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    steps: [
      "לסדר בתחתית סיר רחב פרוסות פלפל ועגבנייה. הן המצע שמונע מהדג להידבק ומהתחתית להישרף.",
      "לפזר שום פרוס, גרגירי חומוס, פפריקה, כורכום וכמון, ולצקת חצי כוס מים ושמן זית.",
      "לבשל את הרוטב 10 דקות מכוסה עד שהפלפל מתרכך.",
      "להניח את פרוסות הדג מעל הירקות ולא לטבול אותן. לבשל 12 דקות מכוסה בלי לערבב.",
      "לפזר כוסברה ופלפל חריף ולכבות. הדג מסיים להתבשל בסיר הסגור.",
    ],
    prep_ahead: [],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.tuna_can",
    name_he: "טונה שימורים",
    role: "protein",
    kosher: "parve",
    effort: "low",
    time_min: 3,
    ingredients: [
      { ingredient_id: "ing.canned_tuna", qty: 80, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 5, unit: "ml" },
      { ingredient_id: "ing.lemon", qty: 0.25, unit: "unit" },
      { ingredient_id: "ing.salt", qty: 1, unit: "g" },
    ],
    steps: [
      "לפתוח ולסנן היטב. טונה שלא נוקזה מרטיבה כל מה שמערבבים איתה.",
      "לפורר לקערה ולערבב עם שמן זית, לימון ומלח.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.entrecote_steak",
    name_he: "סטייק אנטריקוט",
    role: "protein",
    kosher: "meat",
    effort: "medium",
    time_min: 15,
    ingredients: [
      { ingredient_id: "ing.entrecote", qty: 250, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.salt", qty: 4, unit: "g" },
      { ingredient_id: "ing.black_pepper", qty: 2, unit: "g" },
    ],
    steps: [
      "להוציא מהמקרר 30 דקות לפני. בשר קר נצרב מבחוץ ונשאר קר במרכז.",
      "לייבש היטב, ולמלוח רק לפני שהוא נכנס למחבת.",
      "לצרוב במחבת ברזל לוהטת 3 דקות לכל צד למדיום־רייר, בלי להזיז.",
      "להוסיף שום ושמן זית בדקה האחרונה ולהרטיב את הסטייק בכף.",
      "לנוח 5 דקות על קרש לפני חיתוך. חיתוך מיידי מוציא את כל הנוזלים לצלחת.",
    ],
    prep_ahead: ["להוציא מהמקרר חצי שעה לפני"],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.roast_chicken",
    name_he: "עוף בתנור",
    role: "protein",
    kosher: "meat",
    effort: "low",
    time_min: 60,
    ingredients: [
      { ingredient_id: "ing.whole_chicken", qty: 350, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.paprika", qty: 5, unit: "g" },
      { ingredient_id: "ing.garlic", qty: 3, unit: "unit" },
      { ingredient_id: "ing.lemon", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.salt", qty: 4, unit: "g" },
      { ingredient_id: "ing.black_pepper", qty: 1, unit: "g" },
    ],
    steps: [
      "לחמם תנור ל-200 מעלות.",
      "לייבש את חלקי העוף ולשפשף בשמן זית, פפריקה, שום כתוש ומלח.",
      "לסדר בתבנית עם העור כלפי מעלה בלי לצופף. חלקים צמודים מתאדים במקום להשחים.",
      "לאפות 45 דקות, ובעשר האחרונות להעלות ל-220 לעור פריך.",
      "לסחוט לימון על העוף החם.",
    ],
    prep_ahead: ["לתבל מהערב — לילה בתיבול עושה את ההבדל"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.pargit",
    name_he: "פרגית",
    role: "protein",
    kosher: "meat",
    effort: "low",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.chicken_thigh", qty: 200, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.paprika", qty: 4, unit: "g" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.lemon", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
      { ingredient_id: "ing.black_pepper", qty: 1, unit: "g" },
    ],
    steps: [
      "לפתוח את הפרגיות לעובי אחיד ולייבש.",
      "לתבל בשמן זית, פפריקה, שום ומלח, ולהשהות 30 דקות.",
      "לצלות על גריל לוהט 5 דקות לכל צד, מתחילים מצד העור.",
      "לסחוט לימון בסוף.",
    ],
    prep_ahead: ["לתבל מראש ולהחזיק במקרר"],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.kebab",
    name_he: "קבב",
    role: "protein",
    kosher: "meat",
    effort: "medium",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.ground_beef", qty: 180, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.parsley", qty: 15, unit: "g" },
      { ingredient_id: "ing.cumin", qty: 3, unit: "g" },
      { ingredient_id: "ing.paprika", qty: 3, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
      { ingredient_id: "ing.black_pepper", qty: 1, unit: "g" },
    ],
    steps: [
      "לקצוץ בצל ופטרוזיליה דק מאוד, ולסחוט מהבצל את הנוזלים. בצל רטוב מפרק את הקבב על הגריל.",
      "ללוש עם הבשר, כמון, פפריקה ומלח עד שהתערובת נדבקת ליד.",
      "לקרר 30 דקות ורק אז לעצב על שיפוד או כאצבע.",
      "לצלות על אש גבוהה 4 דקות לכל צד, ולהפוך פעם אחת בלבד.",
    ],
    prep_ahead: ["לעצב את הקבב מראש ולהחזיק במקרר"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.shawarma_meat",
    name_he: "שווארמה",
    role: "protein",
    kosher: "meat",
    effort: "medium",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.chicken_thigh", qty: 200, unit: "g" },
      { ingredient_id: "ing.shawarma_spice", qty: 5, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "לפרוס את ירך העוף לרצועות דקות.",
      "לערבב עם תערובת שווארמה, שמן זית ובצל פרוס, ולהשרות שעה לפחות.",
      "לצרוב במחבת לוהטת בשתי מנות. מחבת עמוסה מוציאה נוזלים והבשר מתבשל במקום להשחים.",
      "לסיים על אש גבוהה עד שהקצוות מתקרמלים.",
    ],
    prep_ahead: ["להשרות את העוף מהערב"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.pasta_tomato_side",
    name_he: "פסטה ברוטב עגבניות",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.pasta", qty: 90, unit: "g" },
      { ingredient_id: "ing.tomato_paste", qty: 40, unit: "g" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "לבשל את הפסטה במים מלוחים, דקה פחות ממה שכתוב על החבילה.",
      "לחמם שום פרוס בשמן זית עד שהוא מבשם, ולהוסיף רסק.",
      "להעביר את הפסטה לרוטב עם שתי כפות ממי הבישול. העמילן שבהם הוא מה שמחבר רוטב לפסטה.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.pasta_butter",
    name_he: "פסטה בחמאה",
    role: "side",
    kosher: "dairy",
    effort: "low",
    time_min: 15,
    ingredients: [
      { ingredient_id: "ing.pasta", qty: 90, unit: "g" },
      { ingredient_id: "ing.butter", qty: 20, unit: "g" },
      { ingredient_id: "ing.parmesan", qty: 15, unit: "g" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
      { ingredient_id: "ing.black_pepper", qty: 1, unit: "g" },
    ],
    steps: [
      "לבשל את הפסטה ולשמור חצי כוס ממי הבישול לפני הסינון.",
      "להמיס חמאה במחבת, להוסיף את הפסטה ומעט ממי הבישול, ולערבב עד שנוצר רוטב.",
      "לפזר פרמזן מחוץ לאש. פרמזן שנכנס על אש גבוהה נקרש לגושים.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.pasta_pesto",
    name_he: "פסטה בפסטו",
    role: "side",
    kosher: "dairy",
    effort: "low",
    time_min: 15,
    ingredients: [
      { ingredient_id: "ing.pasta", qty: 90, unit: "g" },
      { ingredient_id: "ing.pesto", qty: 40, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 5, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "לבשל את הפסטה ולשמור מעט ממי הבישול.",
      "לערבב את הפסטו מחוץ לאש. פסטו שמתבשל מאבד את הצבע ואת הריח.",
      "לדלל בכף ממי הבישול, עד שהרוטב נצמד לפסטה.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.brown_rice_side",
    name_he: "אורז מלא",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 45,
    ingredients: [
      { ingredient_id: "ing.brown_rice", qty: 80, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 5, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "לשטוף עד שהמים יוצאים צלולים.",
      "לבשל ביחס כוס אורז לשתי כוסות מים, 35 דקות מכוסה על אש נמוכה.",
      "לכבות ולתת לעמוד 10 דקות מכוסה לפני שפותחים.",
    ],
    prep_ahead: [],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.quinoa_side",
    name_he: "קינואה",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.quinoa", qty: 60, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 5, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "לשטוף היטב במסננת. הציפוי הטבעי של הקינואה מר, ושטיפה מורידה אותו.",
      "לקלות דקה בסיר יבש עד ריח אגוזי.",
      "להוסיף מים ביחס אחד לשניים ולבשל 15 דקות מכוסה.",
      "לנפח במזלג ולא בכף.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.chickpeas_side",
    name_he: "גרגירי חומוס",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 70,
    ingredients: [
      { ingredient_id: "ing.chickpeas", qty: 80, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.cumin", qty: 2, unit: "g" },
      { ingredient_id: "ing.lemon", qty: 0.25, unit: "unit" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "להשרות בלילה, ולבשל כשעה עד שהגרגיר נמעך בין שתי אצבעות.",
      "לסנן ולערבב חם עם שמן זית, כמון, לימון ומלח. גרגיר חם סופג תיבול, קר רק נרטב.",
    ],
    prep_ahead: ["להשרות בלילה"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.mexican_beans",
    name_he: "שעועית מקסיקנית",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.canned_beans", qty: 200, unit: "g" },
      { ingredient_id: "ing.onion", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.tomato_paste", qty: 30, unit: "g" },
      { ingredient_id: "ing.corn", qty: 40, unit: "g" },
      { ingredient_id: "ing.cumin", qty: 3, unit: "g" },
      { ingredient_id: "ing.paprika", qty: 3, unit: "g" },
      { ingredient_id: "ing.hot_pepper", qty: 0.25, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "לטגן בצל קצוץ עד שהוא מזהיב, ולהוסיף שום, כמון ופפריקה לחצי דקה.",
      "להוסיף רסק, שעועית מסוננת ותירס, ומעט מים.",
      "לבשל 15 דקות על אש נמוכה.",
      "למעוך חלק מהשעועית בכף. זה מה שמסמיך את התבשיל בלי קמח.",
    ],
    prep_ahead: [],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.roasted_cauliflower",
    name_he: "כרובית בתנור",
    role: "veg",
    kosher: "parve",
    effort: "low",
    time_min: 35,
    ingredients: [
      { ingredient_id: "ing.cauliflower", qty: 300, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 20, unit: "ml" },
      { ingredient_id: "ing.paprika", qty: 2, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    steps: [
      "לפרק לפרחים בגודל אחיד ולייבש.",
      "לערבב בשמן זית ומלח, ולפזר בתבנית בשכבה אחת. פרחים שנוגעים זה בזה מתאדים במקום להשחים.",
      "לאפות 220 מעלות 25 דקות בלי לערבב, עד שהקצוות שחומים.",
    ],
    prep_ahead: [],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.green_beans_side",
    name_he: "שעועית ירוקה",
    role: "veg",
    kosher: "parve",
    effort: "low",
    time_min: 15,
    ingredients: [
      { ingredient_id: "ing.green_beans", qty: 200, unit: "g" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.lemon", qty: 0.25, unit: "unit" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "לחלוט 4 דקות במים רותחים מלוחים, ולהעביר מיד למי קרח. זה מה ששומר על הירוק.",
      "לייבש ולהקפיץ במחבת עם שמן זית ושום עד שהשום מזהיב.",
      "לסחוט לימון בסוף.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.antipasti",
    name_he: "אנטיפסטי",
    role: "veg",
    kosher: "parve",
    effort: "medium",
    time_min: 35,
    ingredients: [
      { ingredient_id: "ing.eggplant", qty: 150, unit: "g" },
      { ingredient_id: "ing.bell_pepper", qty: 1, unit: "unit" },
      { ingredient_id: "ing.zucchini", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.sun_dried_tomato", qty: 20, unit: "g" },
      { ingredient_id: "ing.garlic", qty: 2, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 25, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    steps: [
      "לחתוך את הירקות לפרוסות בעובי סנטימטר.",
      "לצלות בתנור 220 מעלות 25 דקות, או על גריל עד סימני חריכה.",
      "לערבב חם עם שמן זית, שום כתוש ומלח. ירק חם סופג את השמן, קר רק נרטב בו.",
      "להגיש בטמפרטורת החדר. אנטיפסטי ישר מהמקרר כמעט חסר טעם.",
    ],
    prep_ahead: ["נשמר במקרר עד שלושה ימים, ומשתפר ביום השני"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.baguette_side",
    name_he: "באגט",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 6,
    ingredients: [{ ingredient_id: "ing.baguette", qty: 80, unit: "g" }],
    steps: ["לחמם בתנור 180 מעלות 5 דקות. באגט שהתרכך חוזר לפריכות בחום יבש, לא במיקרוגל."],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.challah_side",
    name_he: "חלה",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 3,
    ingredients: [{ ingredient_id: "ing.challah", qty: 80, unit: "g" }],
    steps: ["לפרוס בסכין משוננת בתנועת ניסור, בלי ללחוץ. לחיצה מועכת את הפרוסה."],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.frena_side",
    name_he: "פרנה",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 5,
    ingredients: [{ ingredient_id: "ing.frena", qty: 100, unit: "g" }],
    steps: ["לחמם על מחבת יבשה 2 דקות לכל צד, עד שהיא מתנפחת מעט."],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.roll_side",
    name_he: "לחמנייה",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 4,
    ingredients: [{ ingredient_id: "ing.roll", qty: 1, unit: "unit" }],
    steps: ["לחצות ולחמם על מחבת בצד החתוך, עד שהוא מזהיב."],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.whole_bread_side",
    name_he: "לחם מלא",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 2,
    ingredients: [{ ingredient_id: "ing.whole_bread", qty: 2, unit: "unit" }],
    steps: ["לפרוס. לחם מלא יבש חוזר לעצמו בטוסטר, לא בחימום ארוך."],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.spelt_bread_side",
    name_he: "לחם כוסמין",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 2,
    ingredients: [{ ingredient_id: "ing.spelt_bread", qty: 2, unit: "unit" }],
    steps: ["לפרוס דק. כוסמין מתפורר יותר מחיטה, וסכין משוננת עוזרת."],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.rye_bread_side",
    name_he: "לחם שיפון",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 2,
    ingredients: [{ ingredient_id: "ing.rye_bread", qty: 2, unit: "unit" }],
    steps: ["לפרוס דק. שיפון כבד וצפוף, ופרוסה עבה משתלטת על הצלחת."],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.cheese_plate",
    name_he: "גבינות",
    role: "side",
    kosher: "dairy",
    effort: "low",
    time_min: 5,
    ingredients: [
      { ingredient_id: "ing.feta", qty: 40, unit: "g" },
      { ingredient_id: "ing.yellow_cheese", qty: 30, unit: "g" },
      { ingredient_id: "ing.goat_cheese", qty: 30, unit: "g" },
      { ingredient_id: "ing.olives", qty: 20, unit: "g" },
    ],
    steps: [
      "להוציא מהמקרר 20 דקות לפני ההגשה. גבינה קרה כמעט חסרת טעם.",
      "לפרוס ולסדר על קרש עם זיתים.",
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.white_cheese_spread",
    name_he: "גבינה לבנה",
    role: "dip",
    kosher: "dairy",
    effort: "low",
    time_min: 2,
    ingredients: [
      { ingredient_id: "ing.white_cheese", qty: 100, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 5, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 1, unit: "g" },
    ],
    steps: ["להוציא לקערית, לזלף שמן זית ולפזר מלח וזעתר אם יש."],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
];

/** פרופילי ברירת מחדל — נזרעים למצב המשתמש בטעינה הראשונה. */
export const DEFAULT_PROFILES = [
  {
    id: "p1",
    name_he: "ירין",
    targets: { kcal: 2200, protein_g: 150, fat_g: 70, carbs_g: 230 },
    dislikes: [],
  },
  {
    id: "p2",
    name_he: "בן/בת הזוג",
    targets: { kcal: 1800, protein_g: 110, fat_g: 60, carbs_g: 190 },
    dislikes: [],
  },
];

const INGREDIENT_BY_ID = new Map(INGREDIENTS.map((ing) => [ing.id, ing]));
const DISH_BY_ID = new Map(DISHES.map((dish) => [dish.id, dish]));

export function getIngredient(id) {
  return INGREDIENT_BY_ID.get(id) || null;
}

export function getDish(id) {
  return DISH_BY_ID.get(id) || null;
}

export function getShelfName(id) {
  const shelf = SHELVES.find((s) => s.id === id);
  return shelf ? shelf.name_he : id;
}
