/* נתוני זרע לשלב א' — קבועים בקוד, לא ב-localStorage.
   ה-store מחזיק מצב משתמש בלבד (תוכנית, פרופילים, מזווה), ולכן אין כאן
   מה להגר בשדרוג. עריכת מנות אינה בשלב א'.

   מוסכמה: nutrition_per_100 הוא תמיד לכל 100 של יחידת הבסיס. כל מצרכי הזרע
   נשמרים בגרמים, כך שהמאקרו הוא לכל 100 גרם. המנוע תומך גם ב-ml וב-unit
   כיחידת בסיס — מסלולים אלה מכוסים בעמוד הבדיקות. */

/** סדר המדפים ברשימת הקניות — הסדר שבו עוברים בסופר. */
export const SHELVES = [
  { id: "produce", name_he: "ירקות ופירות" },
  { id: "meat", name_he: "בשר ועוף" },
  { id: "fish", name_he: "דגים" },
  { id: "dairy_eggs", name_he: "מוצרי חלב וביצים" },
  { id: "chilled", name_he: "ממרחים וסלטים מוכנים" },
  { id: "dry_goods", name_he: "מוצרים יבשים" },
  { id: "pantry", name_he: "מזווה" },
];

export const INGREDIENTS = [
  {
    id: "ing.chicken_breast",
    name_he: "חזה עוף",
    aliases: ["פילה עוף", "חזה עוף טרי"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "meat",
    kosher: "meat",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 165, protein_g: 31, fat_g: 3.6, carbs_g: 0 },
  },
  {
    id: "ing.onion",
    name_he: "בצל",
    aliases: ["בצל יבש", "בצל לבן"],
    base_unit: "g",
    unit_weight_g: 150,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 40, protein_g: 1.1, fat_g: 0.1, carbs_g: 9.3 },
  },
  {
    id: "ing.egg",
    name_he: "ביצה",
    aliases: ["ביצים"],
    base_unit: "g",
    unit_weight_g: 55,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 143, protein_g: 12.6, fat_g: 9.5, carbs_g: 0.7 },
  },
  {
    id: "ing.rice",
    name_he: "אורז לבן",
    aliases: ["אורז"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 360, protein_g: 6.6, fat_g: 0.6, carbs_g: 79 },
  },
  {
    id: "ing.tomato",
    name_he: "עגבנייה",
    aliases: ["עגבניות"],
    base_unit: "g",
    unit_weight_g: 120,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 18, protein_g: 0.9, fat_g: 0.2, carbs_g: 3.9 },
  },
  {
    id: "ing.potato",
    name_he: "תפוח אדמה",
    aliases: ["תפוחי אדמה", "תפו״א"],
    base_unit: "g",
    unit_weight_g: 170,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 77, protein_g: 2, fat_g: 0.1, carbs_g: 17 },
  },
  {
    id: "ing.breadcrumbs",
    name_he: "פירורי לחם",
    aliases: ["פירורי ציפוי"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 395, protein_g: 13, fat_g: 5.3, carbs_g: 72 },
  },
  {
    // גביע יוגורט — משקל היחידה משתנה בין מותגים, ולכן unit_weight_g נשאר null.
    // מנה שנוקבת "1 יח'" תיפול למסלול "לבדוק ידנית" במקום להמציא המרה.
    id: "ing.yogurt",
    name_he: "יוגורט טבעי",
    aliases: ["גביע יוגורט"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 61, protein_g: 3.5, fat_g: 3.3, carbs_g: 4.7 },
  },
  {
    id: "ing.olive_oil",
    name_he: "שמן זית",
    aliases: ["שמן"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: 0.91,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 884, protein_g: 0, fat_g: 100, carbs_g: 0 },
  },
  {
    id: "ing.salt",
    name_he: "מלח",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 0, protein_g: 0, fat_g: 0, carbs_g: 0 },
  },
  {
    id: "ing.ground_beef",
    name_he: "בשר בקר טחון",
    aliases: ["בקר טחון", "טחון"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "meat",
    kosher: "meat",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 254, protein_g: 17, fat_g: 20, carbs_g: 0 },
  },
  {
    // דג הוא פרווה בכשרות, גם כשהוא יושב במדף ליד הבשר.
    id: "ing.salmon",
    name_he: "פילה סלמון",
    aliases: ["סלמון"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "fish",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 208, protein_g: 20, fat_g: 13, carbs_g: 0 },
  },
  {
    id: "ing.cucumber",
    name_he: "מלפפון",
    aliases: ["מלפפונים"],
    base_unit: "g",
    unit_weight_g: 120,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 15, protein_g: 0.7, fat_g: 0.1, carbs_g: 3.6 },
  },
  {
    // ראש חסה נע בין 300 ל-700 גרם, ולכן unit_weight_g נשאר null:
    // "חסה אחת" תגיע לרשימה כפריט להכרעה במקום כמספר מומצא.
    id: "ing.lettuce",
    name_he: "חסה",
    aliases: ["עלי חסה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 15, protein_g: 1.4, fat_g: 0.2, carbs_g: 2.9 },
  },
  {
    id: "ing.zucchini",
    name_he: "קישוא",
    aliases: ["קישואים"],
    base_unit: "g",
    unit_weight_g: 200,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 17, protein_g: 1.2, fat_g: 0.3, carbs_g: 3.1 },
  },
  {
    id: "ing.sweet_potato",
    name_he: "בטטה",
    aliases: ["בטטות"],
    base_unit: "g",
    unit_weight_g: 200,
    density_g_per_ml: null,
    shelf: "produce",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 86, protein_g: 1.6, fat_g: 0.1, carbs_g: 20 },
  },
  {
    id: "ing.pasta",
    name_he: "פסטה",
    aliases: ["ספגטי", "פנה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 371, protein_g: 13, fat_g: 1.5, carbs_g: 75 },
  },
  {
    id: "ing.couscous",
    name_he: "קוסקוס",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 376, protein_g: 12.8, fat_g: 0.6, carbs_g: 77 },
  },
  {
    id: "ing.pita",
    name_he: "פיתה",
    aliases: ["פיתות"],
    base_unit: "g",
    unit_weight_g: 70,
    density_g_per_ml: null,
    shelf: "dry_goods",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 275, protein_g: 9, fat_g: 1.2, carbs_g: 55 },
  },
  {
    id: "ing.tahini",
    name_he: "טחינה גולמית",
    aliases: ["טחינה"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "pantry",
    kosher: "parve",
    pantry_staple: true,
    gtin: null,
    nutrition_per_100: { kcal: 595, protein_g: 17, fat_g: 53, carbs_g: 21 },
  },
  {
    id: "ing.hummus",
    name_he: "חומוס מוכן",
    aliases: ["חומוס"],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "chilled",
    kosher: "parve",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 166, protein_g: 8, fat_g: 10, carbs_g: 14 },
  },
  {
    id: "ing.butter",
    name_he: "חמאה",
    aliases: [],
    base_unit: "g",
    unit_weight_g: null,
    density_g_per_ml: null,
    shelf: "dairy_eggs",
    kosher: "dairy",
    pantry_staple: false,
    gtin: null,
    nutrition_per_100: { kcal: 717, protein_g: 0.9, fat_g: 81, carbs_g: 0.1 },
  },
];

/* כמויות המנה הן תמיד למנה בודדת אחת. ההכפלה קורה רק בשכבת התוכנית.

   `role` הוא תפקיד הרכיב בצלחת (ראה compose.js). "מנה שלמה" היא ארוחה
   בפני עצמה, והשאר מורכבים זה עם זה. שלוש המנות הראשונות כאן קדמו
   לתפקידים והן נשארות מנות שלמות — לא רק בגלל תאימות: "שניצל וצ'יפס"
   בהקשה אחת הוא קיצור אמיתי לערב שלא רוצים להרכיב בו כלום. */
export const DISHES = [
  {
    id: "dish.schnitzel_chips",
    name_he: "שניצל וצ'יפס",
    role: "main",
    kosher: "meat",
    effort: "medium",
    time_min: 35,
    ingredients: [
      { ingredient_id: "ing.chicken_breast", qty: 150, unit: "g" },
      { ingredient_id: "ing.egg", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.breadcrumbs", qty: 40, unit: "g" },
      { ingredient_id: "ing.potato", qty: 250, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 20, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["לצפות את השניצל מראש"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.rice_veg",
    name_he: "אורז עם בצל ועגבניות",
    role: "main",
    kosher: "parve",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.rice", qty: 80, unit: "g" },
      { ingredient_id: "ing.onion", qty: 2, unit: "unit" },
      { ingredient_id: "ing.tomato", qty: 2, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.veg_omelette",
    name_he: "חביתת ירק עם יוגורט",
    role: "main",
    kosher: "dairy",
    effort: "low",
    time_min: 15,
    ingredients: [
      { ingredient_id: "ing.egg", qty: 2, unit: "unit" },
      { ingredient_id: "ing.onion", qty: 150, unit: "g" },
      { ingredient_id: "ing.tomato", qty: 1, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
      { ingredient_id: "ing.yogurt", qty: 1, unit: "unit" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },

  /* ---------- חלבון ---------- */

  {
    id: "dish.schnitzel",
    name_he: "שניצל עוף",
    role: "protein",
    kosher: "meat",
    effort: "medium",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.chicken_breast", qty: 150, unit: "g" },
      { ingredient_id: "ing.egg", qty: 0.5, unit: "unit" },
      { ingredient_id: "ing.breadcrumbs", qty: 40, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["לצפות את השניצל מראש"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.grilled_chicken",
    name_he: "חזה עוף בגריל",
    role: "protein",
    kosher: "meat",
    effort: "low",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.chicken_breast", qty: 180, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["להשרות את העוף מראש"],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.meatballs",
    name_he: "קציצות בקר",
    role: "protein",
    kosher: "meat",
    effort: "medium",
    time_min: 35,
    ingredients: [
      { ingredient_id: "ing.ground_beef", qty: 150, unit: "g" },
      { ingredient_id: "ing.onion", qty: 40, unit: "g" },
      { ingredient_id: "ing.egg", qty: 0.25, unit: "unit" },
      { ingredient_id: "ing.breadcrumbs", qty: 20, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["לגלגל את הקציצות מראש"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.baked_salmon",
    name_he: "פילה סלמון בתנור",
    role: "protein",
    kosher: "parve",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.salmon", qty: 160, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: [],
    macros_override: null,
  },
  {
    id: "dish.omelette",
    name_he: "חביתה",
    role: "protein",
    kosher: "parve",
    effort: "low",
    time_min: 10,
    ingredients: [
      { ingredient_id: "ing.egg", qty: 2, unit: "unit" },
      { ingredient_id: "ing.olive_oil", qty: 5, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 1, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },

  /* ---------- תוספת ---------- */

  {
    id: "dish.oven_chips",
    name_he: "צ'יפס בתנור",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 30,
    ingredients: [
      { ingredient_id: "ing.potato", qty: 250, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: ["לחתוך את תפוחי האדמה מראש"],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.white_rice",
    name_he: "אורז לבן",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 20,
    ingredients: [
      { ingredient_id: "ing.rice", qty: 80, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 5, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.mashed_potato",
    name_he: "פירה",
    role: "side",
    kosher: "dairy",
    effort: "low",
    time_min: 25,
    ingredients: [
      { ingredient_id: "ing.potato", qty: 250, unit: "g" },
      { ingredient_id: "ing.butter", qty: 15, unit: "g" },
      { ingredient_id: "ing.salt", qty: 3, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["comfort"],
    macros_override: null,
  },
  {
    id: "dish.pasta_plain",
    name_he: "פסטה",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 15,
    ingredients: [
      { ingredient_id: "ing.pasta", qty: 90, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.couscous_side",
    name_he: "קוסקוס",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 10,
    ingredients: [
      { ingredient_id: "ing.couscous", qty: 80, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.warm_pita",
    name_he: "פיתה חמה",
    role: "side",
    kosher: "parve",
    effort: "low",
    time_min: 5,
    ingredients: [{ ingredient_id: "ing.pita", qty: 1, unit: "unit" }],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },

  /* ---------- ירק וסלט ---------- */

  {
    id: "dish.israeli_salad",
    name_he: "סלט ישראלי",
    role: "veg",
    kosher: "parve",
    effort: "low",
    time_min: 10,
    ingredients: [
      { ingredient_id: "ing.tomato", qty: 120, unit: "g" },
      { ingredient_id: "ing.cucumber", qty: 100, unit: "g" },
      { ingredient_id: "ing.onion", qty: 25, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 1, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.green_salad",
    name_he: "סלט עלים",
    role: "veg",
    kosher: "parve",
    effort: "low",
    time_min: 5,
    ingredients: [
      { ingredient_id: "ing.lettuce", qty: 60, unit: "g" },
      { ingredient_id: "ing.cucumber", qty: 60, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 10, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 1, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.roasted_veg",
    name_he: "ירקות בתנור",
    role: "veg",
    kosher: "parve",
    effort: "low",
    time_min: 40,
    ingredients: [
      { ingredient_id: "ing.sweet_potato", qty: 150, unit: "g" },
      { ingredient_id: "ing.zucchini", qty: 120, unit: "g" },
      { ingredient_id: "ing.onion", qty: 60, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 15, unit: "ml" },
      { ingredient_id: "ing.salt", qty: 2, unit: "g" },
    ],
    prep_ahead: ["לחתוך את הירקות מראש"],
    tags: [],
    macros_override: null,
  },

  /* ---------- מטבל ורוטב ---------- */

  {
    id: "dish.tahini_sauce",
    name_he: "טחינה",
    role: "dip",
    kosher: "parve",
    effort: "low",
    time_min: 5,
    ingredients: [
      { ingredient_id: "ing.tahini", qty: 30, unit: "g" },
      { ingredient_id: "ing.salt", qty: 1, unit: "g" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
  {
    id: "dish.hummus_side",
    name_he: "חומוס",
    role: "dip",
    kosher: "parve",
    effort: "low",
    time_min: 5,
    ingredients: [
      { ingredient_id: "ing.hummus", qty: 100, unit: "g" },
      { ingredient_id: "ing.olive_oil", qty: 5, unit: "ml" },
    ],
    prep_ahead: [],
    tags: ["quick"],
    macros_override: null,
  },
];

/** פרופילי ברירת מחדל — נזרעים למצב המשתמש בטעינה הראשונה. */
export const DEFAULT_PROFILES = [
  {
    id: "p1",
    name_he: "ירין",
    targets: { kcal: 2200, protein_g: 150, fat_g: 70, carbs_g: 230 },
    dislikes: [],
  },
  {
    id: "p2",
    name_he: "בן/בת הזוג",
    targets: { kcal: 1800, protein_g: 110, fat_g: 60, carbs_g: 190 },
    dislikes: [],
  },
];

const INGREDIENT_BY_ID = new Map(INGREDIENTS.map((ing) => [ing.id, ing]));
const DISH_BY_ID = new Map(DISHES.map((dish) => [dish.id, dish]));

export function getIngredient(id) {
  return INGREDIENT_BY_ID.get(id) || null;
}

export function getDish(id) {
  return DISH_BY_ID.get(id) || null;
}

export function getShelfName(id) {
  const shelf = SHELVES.find((s) => s.id === id);
  return shelf ? shelf.name_he : id;
}
